# The presentation environment (ADR-0015; docs/deployment.md, section 7). Non-secret
# settings only: what identifies you goes in local.tfvars, and secrets are generated by
# Terraform or added by hand (the LLM key).
region      = "us-east1"
name_prefix = "pb"

# Detective mode (ADR-0019): judges see each turn's masked timeline from a switch in the
# customer chat; the back office turns it off and on at runtime.
detective_mode = true
