"""Dataset ingestion: data/raw/<source> → data/staging/<source> + quality report."""

import json
import os
import shutil
from collections.abc import Callable
from datetime import UTC, date, datetime
from pathlib import Path

from banking_core.seed.ingest.factored import (
    IngestOptions,
    IngestResult,
    StagingRecord,
    ingest_factored,
)
from banking_core.seed.ingest.mapping import SourceMapping, load_mapping
from banking_core.seed.staging import load_and_validate_staging

DEFAULT_MAX_CUSTOMERS = 5000
MANIFEST = "manifest.json"
STAGING_FILES = ("customers", "accounts", "cards", "transactions")

Adapter = Callable[[Path, SourceMapping, IngestOptions], IngestResult]
ADAPTERS: dict[str, Adapter] = {"factored": ingest_factored}


def options_from_env(salt: str | bytes | None = None) -> IngestOptions:
    """INGEST_MAX_CUSTOMERS (0 = all), INGEST_ANCHOR_DATE (default: today, UTC)."""
    raw_cap = os.getenv("INGEST_MAX_CUSTOMERS", "").strip()
    max_customers = int(raw_cap) if raw_cap else DEFAULT_MAX_CUSTOMERS
    if max_customers < 0:
        raise ValueError("INGEST_MAX_CUSTOMERS must be 0 (no cap) or positive")
    raw_anchor = os.getenv("INGEST_ANCHOR_DATE", "").strip()
    anchor = date.fromisoformat(raw_anchor) if raw_anchor else datetime.now(UTC).date()
    resolved_salt = salt or os.getenv("BLIND_INDEX_SALT")
    if not resolved_salt:
        raise ValueError("BLIND_INDEX_SALT is required to pseudonymize emails")
    return IngestOptions(max_customers=max_customers, anchor=anchor, salt=resolved_salt)


def run_ingest(
    source: str,
    raw_root: Path,
    staging_root: Path,
    report_path: Path,
    options: IngestOptions,
) -> IngestResult:
    """Rebuild data/staging/<source> from data/raw/<source>; idempotent."""
    mapping = load_mapping(source)
    adapter = ADAPTERS.get(mapping.adapter)
    if adapter is None:
        raise ValueError(f"unknown ingest adapter '{mapping.adapter}'")
    raw_dir = raw_root / source
    if not raw_dir.is_dir():
        raise FileNotFoundError(f"raw data for '{source}' not found at {raw_dir}")

    result = adapter(raw_dir, mapping, options)

    # Write to a sibling directory, validate it, then swap it in.
    staging_root.mkdir(parents=True, exist_ok=True)
    target = staging_root / source
    tmp = staging_root / f".{source}.tmp"
    shutil.rmtree(tmp, ignore_errors=True)
    tmp.mkdir()
    records: dict[str, list[StagingRecord]] = {
        "customers": result.customers,
        "accounts": result.accounts,
        "cards": result.cards,
        "transactions": result.transactions,
    }
    for name in STAGING_FILES:
        with open(tmp / f"{name}.jsonl", "w", encoding="utf-8") as f:
            for record in records[name]:
                f.write(json.dumps(record, ensure_ascii=False) + "\n")
    load_and_validate_staging(tmp, origin="dataset", source=source)
    (tmp / MANIFEST).write_text(
        json.dumps(
            {
                "source": source,
                "origin": "dataset",
                "anchor_date": options.anchor.isoformat(),
                "dataset_cutoff": mapping.dataset_cutoff.isoformat(),
                "shift_days": result.shift_days,
                "max_customers": options.max_customers,
                "counts": {n: len(records[n]) for n in STAGING_FILES},
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    shutil.rmtree(target, ignore_errors=True)
    tmp.rename(target)

    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(render_report(mapping, options, result), encoding="utf-8")
    return result


def staged_sources(staging_root: Path) -> list[str]:
    """Sources with a complete staging directory (manifest written last)."""
    if not staging_root.is_dir():
        return []
    return sorted(
        p.name
        for p in staging_root.iterdir()
        if p.is_dir() and not p.name.startswith(".") and (p / MANIFEST).is_file()
    )


def render_report(
    mapping: SourceMapping, options: IngestOptions, result: IngestResult
) -> str:
    cap = options.max_customers or "none (full volume)"
    lines = [
        f"# Data quality: `{mapping.source}` ingest",
        "",
        "Generated by `make ingest SOURCE="
        f"{mapping.source}`. Aggregates only: no rows, identifiers or PII.",
        "",
        "## Run",
        "",
        "| Parameter | Value |",
        "|---|---|",
        f"| Mapping | `banking_core/seed/ingest/sources/{mapping.source}.json` |",
        f"| Dataset cutoff | {mapping.dataset_cutoff.isoformat()} |",
        f"| Anchor date (`INGEST_ANCHOR_DATE`) | {options.anchor.isoformat()} |",
        f"| Date shift (anchor − cutoff) | {result.shift_days} days |",
        f"| History window | last {mapping.history_days} days before the cutoff |",
        f"| Customer cap (`INGEST_MAX_CUSTOMERS`) | {cap} |",
        "",
        "Timestamps after the cutoff are clamped to just before it, then every "
        "event timestamp is shifted by the same number of days so the history "
        "ends at the anchor. Birth dates are not shifted; card expiry is shifted "
        "but not clamped.",
        "",
        "## Counts per rule",
        "",
        "| Rule | Rows |",
        "|---|---:|",
    ]
    for rule in sorted(result.counts):
        lines.append(f"| {rule} | {result.counts[rule]:,} |")
    lines += [
        "",
        "Collisions with the synthetic demo identities are resolved at `make seed` "
        "(demo wins) and printed by that command.",
    ]
    if result.thresholds:
        lines += [
            "",
            "## Policy thresholds derived from `daily_exchange_rates`",
            "",
            "| Currency | Computation | Threshold (minor units) |",
            "|---|---|---:|",
        ]
        for t in result.thresholds:
            lines.append(
                f"| {t['currency']} | {t['base_amount_minor']} {t['base_currency']} "
                f"minor × {t['rate']} ({t['base_currency']}→{t['currency']}, "
                f"{t['rate_date']}) | {t['threshold_minor']:,} |"
            )
        lines += [
            "",
            "These values are seeded through `POLICY_SEED_THRESHOLDS_MINOR` "
            "(`.env.example`, compose); the policy engine reads them from its "
            "configuration, never from this report.",
        ]
    return "\n".join(lines) + "\n"
