"""Portuguese templates for intent and slot generation.

Contains:
- 15 intents
- 40 train templates/phrases per intent
- 10 validation templates/phrases per intent (strictly disjoint from train)
- Varied linguistic registers, casing, colloquialisms, and common typos.
"""

Template = list[str | tuple[str, str]]

TRAIN_TEMPLATES: dict[str, list[Template]] = {
    "report_unrecognized_charge": [
        [
            "Tem uma compra de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " na ",
            ("merchant", "merchant"),
            " que não fui eu quem fez no cartão ",
            ("card_last4", "card_last4"),
        ],
        [
            "Não reconheço um lançamento de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " no estabelecimento ",
            ("merchant", "merchant"),
            " no dia ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "ola desconheco uma cobranca de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " na ",
            ("merchant", "merchant"),
        ],
        [
            "URGENTE: compra desconhecida de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " na ",
            ("merchant", "merchant"),
            " no cartão final ",
            ("card_last4", "card_last4"),
        ],
        [
            "Apareceu um débito não autorizado no ",
            ("merchant", "merchant"),
            " no valor de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
        ],
        [
            "foi cobrado ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " na ",
            ("merchant", "merchant"),
            " e eu nao comprei nada",
        ],
        [
            "Desconheço a transação de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " em ",
            ("merchant", "merchant"),
            " no meu cartão ",
            ("card_last4", "card_last4"),
        ],
        [
            "Reporto uma cobrança indevida da ",
            ("merchant", "merchant"),
            " de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " realizada ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "alguem usou meu cartao final ",
            ("card_last4", "card_last4"),
            " para pagar ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " na ",
            ("merchant", "merchant"),
        ],
        [
            "Tem um valor estranho de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " faturado por ",
            ("merchant", "merchant"),
            " que não autorizei",
        ],
        [
            "não reconheço essa compra no ",
            ("merchant", "merchant"),
            " por ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
        ],
        [
            "Aviso de transação desconhecida: ",
            ("merchant", "merchant"),
            " cobrou ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " no cartão ",
            ("card_last4", "card_last4"),
        ],
        [
            "vejo na minha fatura uma compra de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " na ",
            ("merchant", "merchant"),
            " que nao fiz",
        ],
        [
            "Identifiquei um lançamento indevido em ",
            ("merchant", "merchant"),
            " de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " em ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "desconheco o debito de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " da loja ",
            ("merchant", "merchant"),
        ],
        [
            "Cobrança não identificada de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " no ",
            ("merchant", "merchant"),
            " cartão ",
            ("card_last4", "card_last4"),
        ],
        [
            "Quero relatar um pagamento fraudulento de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " na ",
            ("merchant", "merchant"),
        ],
        [
            "Recebi notificação de cobrança de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " em ",
            ("merchant", "merchant"),
            " mas não fiz essa compra",
        ],
        [
            "consta uma compra estranha na ",
            ("merchant", "merchant"),
            " de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
        ],
        [
            "Cobrança indevida no cartão final ",
            ("card_last4", "card_last4"),
            " no valor de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " em ",
            ("merchant", "merchant"),
        ],
    ],
    "report_lost_card": [
        [
            "Perdi meu cartão final ",
            ("card_last4", "card_last4"),
            " no shopping e não acho mais",
        ],
        [
            "Extraviei meu cartão terminado em ",
            ("card_last4", "card_last4"),
            " e não encontro em lugar nenhum",
        ],
        ["acho que perdi meu cartao ", ("card_last4", "card_last4"), " no uber ontem"],
        [
            "URGENTE: perdi meu cartão de crédito número ",
            ("card_number", "card_number"),
        ],
        ["Não sei onde deixei meu cartão com final ", ("card_last4", "card_last4")],
        [
            "ola perdi meu cartao ",
            ("card_last4", "card_last4"),
            " como faco para reportar",
        ],
        [
            "Deixei meu cartão final ",
            ("card_last4", "card_last4"),
            " esquecido em um restaurante",
        ],
        [
            "Perdi meu cartão com terminação ",
            ("card_last4", "card_last4"),
            " durante uma viagem",
        ],
        [
            "se me perdeu o cartao final ",
            ("card_last4", "card_last4"),
            " nao consigo achar",
        ],
        [
            "Boa tarde, gostaria de comunicar a perda do meu cartão final ",
            ("card_last4", "card_last4"),
        ],
        [
            "Extravio de cartão: não acho meu cartão de débito ",
            ("card_last4", "card_last4"),
        ],
        ["perdi o cartao ", ("card_last4", "card_last4"), " na rua hoje cedo"],
        ["Perdi minha carteira onde estava o cartão ", ("card_last4", "card_last4")],
        ["Esqueci o meu cartão ", ("card_last4", "card_last4"), " no caixa eletrônico"],
        ["comunicado de perda de cartao final ", ("card_last4", "card_last4")],
        [
            "Não encontro meu cartão com terminação ",
            ("card_last4", "card_last4"),
            " desde cedo",
        ],
        [
            "Perdi meu cartão de crédito ",
            ("card_number", "card_number"),
            " recentemente",
        ],
        ["acho que esqueci meu cartao ", ("card_last4", "card_last4"), " na farmacia"],
        ["Extraviei o cartão de débito ", ("card_last4", "card_last4")],
        [
            "Gostaria de informar que perdi meu cartão com número ",
            ("card_number", "card_number"),
        ],
    ],
    "report_stolen_card": [
        [
            "Fui assaltado no ponto de ônibus e levaram meu cartão final ",
            ("card_last4", "card_last4"),
        ],
        [
            "Meu cartão de crédito final ",
            ("card_last4", "card_last4"),
            " foi roubado hoje cedo",
        ],
        [
            "roubaram minha bolsa com o cartao ",
            ("card_last4", "card_last4"),
            " no metro",
        ],
        [
            "URGENTE: meu cartão de número ",
            ("card_number", "card_number"),
            " foi furtado",
        ],
        [
            "Fui vítima de furto e levaram meu cartão terminado em ",
            ("card_last4", "card_last4"),
        ],
        [
            "levaram minha carteira com meu cartao ",
            ("card_last4", "card_last4"),
            " em um arrastão",
        ],
        [
            "Acabaram de roubar meu cartão de débito com final ",
            ("card_last4", "card_last4"),
        ],
        ["Arrombaram meu carro e roubaram o cartão ", ("card_last4", "card_last4")],
        ["ola fui assaltado e levaram meu cartao ", ("card_last4", "card_last4")],
        [
            "Comunico o roubo à mão armada do meu cartão final ",
            ("card_last4", "card_last4"),
        ],
        [
            "Bandidos levaram meu cartão final ",
            ("card_last4", "card_last4"),
            " agora pouco",
        ],
        [
            "furto de cartao terminado em ",
            ("card_last4", "card_last4"),
            " no transporte coletivo",
        ],
        ["Bateram minha carteira com o cartão final ", ("card_last4", "card_last4")],
        ["acabo de sofrer um assalto, levaram o cartao ", ("card_last4", "card_last4")],
        ["Registro de roubo do meu cartão ", ("card_number", "card_number"), " hoje"],
        [
            "Fui despojado do meu cartão de débito ",
            ("card_last4", "card_last4"),
            " na rua",
        ],
        ["roubo de cartao ", ("card_last4", "card_last4"), " no centro da cidade"],
        ["Criminosos levaram meu cartão terminado em ", ("card_last4", "card_last4")],
        ["levaram meus pertences incluindo o cartao ", ("card_last4", "card_last4")],
        [
            "Notifico o furto do meu cartão com terminação ",
            ("card_last4", "card_last4"),
        ],
    ],
    "report_suspicious_activity": [
        [
            "Recebi um SMS alertando sobre acesso suspeito à minha conta",
        ],
        [
            "Tem atividade suspeita na conta, tentativas falhas de login",
        ],
        [
            "recebi mensagem suspeita pedindo meus dados bancarios do cartao final ",
            ("card_last4", "card_last4"),
        ],
        [
            "Alerta: acessos estranhos à minha conta vindos de outra região",
        ],
        [
            "Identifiquei atividade atípica no aplicativo bancário no dia ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "chegou codigo de seguranca por sms que nao solicitei para minha conta",
        ],
        [
            "Suspeito que clonaram meu cartão ",
            ("card_last4", "card_last4"),
            " após usar um caixa eletrônico",
        ],
        [
            "Recebi notificações consecutivas com tokens de autenticação que não pedi",
        ],
        [
            "atividade estranha na minha conta, avisos de tentativa de troca de senha",
        ],
        [
            "Notifico tentativa de invasão e acessos não autorizados no meu cadastro",
        ],
        [
            "Alerta de golpe: recebi e-mail falso de phishing imitando o banco",
        ],
        [
            "notificacao esquisita de tentativa bloqueada de acesso ao meu aplicativo",
        ],
        [
            "Me avisaram sobre login não reconhecido a partir de um dispositivo novo",
        ],
        [
            "Tentativa suspeita de acesso registrada no dia ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "alerta de golpe ou clonagem no meu cartao ",
            ("card_last4", "card_last4"),
            " por dispositivo suspeito",
        ],
        [
            "Aviso do sistema sobre bloqueio preventivo de segurança no cartão ",
            ("card_last4", "card_last4"),
        ],
        [
            "Acho que estão tentando invadir minha conta com mensagens fraudulentas",
        ],
        [
            "Recebi alertas de segurança sobre acessos com senha incorreta",
        ],
        [
            "suspeita de fraude no cartao ",
            ("card_last4", "card_last4"),
            " após alerta de skimming no terminal",
        ],
        [
            "Avisos suspeitos indicando atividade não reconhecida no meu usuário",
        ],
        [
            "Aviso urgente: alerta de segurança sobre login de celular desconhecido",
        ],
        [
            "Tentam entrar na minha conta bancária, vários avisos de senha errada",
        ],
        [
            "suspeito de fraude no meu cartão ",
            ("card_last4", "card_last4"),
            " depois de passar numa maquininha estranha",
        ],
        [
            "Identifiquei e-mails falsos tentando roubar meus dados de acesso",
        ],
        [
            "ligação suspeita de pessoa fingindo ser do banco pedindo dados",
        ],
        [
            "Movimentação suspeita: tentaram mudar meu telefone cadastrado",
        ],
        [
            "Alerta sobre tentativa de cadastro de um novo aparelho na minha conta em ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "notifiquei sms falso informando bloqueio indevido da minha conta",
        ],
        [
            "Recebi aviso do aplicativo sobre sessão bloqueada por segurança",
        ],
        [
            "Acho que meu cartão final ",
            ("card_last4", "card_last4"),
            " foi clonado ou adulterado",
        ],
        [
            "Atividade atípica: pedidos repetidos de validação que não solicitei",
        ],
        [
            "apareceu alerta no internet banking de acesso de localização estranha",
        ],
        [
            "Registraram tentativas repetidas de alteração de senha no cartão ",
            ("card_last4", "card_last4"),
        ],
        [
            "Aviso do sistema contra tentativa de golpe de phishing no cadastro",
        ],
        [
            "Vejo atividade estranha nos logs de acesso da minha conta no dia ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "suspeita de clonagem em caixa eletronico com cartao ",
            ("card_last4", "card_last4"),
        ],
        [
            "Link suspeito enviado por WhatsApp pedindo confirmação de dados",
        ],
        [
            "Alerta do sistema informando tentativas de biometria inválida",
        ],
        [
            "relato comportamento fora do comum na minha conta com avisos de risco",
        ],
        [
            "Tenho suspeita de golpe digital após mensagens estranhas recebidas hoje",
        ],
    ],
    "request_card_block": [
        [
            "Por favor bloqueiem meu cartão final ",
            ("card_last4", "card_last4"),
            " imediatamente",
        ],
        [
            "Quero congelar meu cartão terminado em ",
            ("card_last4", "card_last4"),
            " por segurança",
        ],
        ["bloquear cartao ", ("card_last4", "card_last4"), " urgente por favor"],
        [
            "URGENTE: bloquear o cartão de número ",
            ("card_number", "card_number"),
            " agora",
        ],
        [
            "Gostaria de suspender preventivamente o meu cartão final ",
            ("card_last4", "card_last4"),
        ],
        ["bloqueiem meu cartao ", ("card_last4", "card_last4"), " agora mesmo"],
        [
            "Solicito o bloqueio definitivo do cartão com final ",
            ("card_last4", "card_last4"),
        ],
        [
            "Coloquem trava de segurança no meu cartão final ",
            ("card_last4", "card_last4"),
        ],
        [
            "por favor bloquear ja o cartao ",
            ("card_last4", "card_last4"),
            " nao quero que usem",
        ],
        ["Preciso inativar o meu cartão terminado em ", ("card_last4", "card_last4")],
        [
            "Bloquear cartão de crédito com final ",
            ("card_last4", "card_last4"),
            " imediatamente",
        ],
        ["por favor congelem o meu cartao ", ("card_last4", "card_last4")],
        [
            "Quero desativar o cartão terminado em ",
            ("card_last4", "card_last4"),
            " no sistema",
        ],
        ["bloqueio urgente de cartao ", ("card_last4", "card_last4")],
        [
            "Solicito o cancelamento e bloqueio do cartão ",
            ("card_number", "card_number"),
        ],
        [
            "Por motivo de segurança peço o bloqueio do cartão ",
            ("card_last4", "card_last4"),
        ],
        ["desativem meu cartao ", ("card_last4", "card_last4"), " com urgencia"],
        [
            "Quero dar baixa e bloquear meu cartão com final ",
            ("card_last4", "card_last4"),
        ],
        [
            "bloqueiem o cartao ",
            ("card_last4", "card_last4"),
            " para nao aprovar compras",
        ],
        ["Bloqueio imediato do cartão de débito ", ("card_last4", "card_last4")],
    ],
    "request_dispute": [
        [
            "Quero contestar essa transação na ",
            ("merchant", "merchant"),
            " de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " e solicitar estorno",
        ],
        [
            "Solicito abertura de disputa para a cobrança indevida no ",
            ("merchant", "merchant"),
            " do dia ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "quero pedir estorno da compra de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " no ",
            ("merchant", "merchant"),
        ],
        [
            "Solicito formalmente o reembolso de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " debitado pela ",
            ("merchant", "merchant"),
        ],
        [
            "Quero contestar uma compra duplicada de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " na ",
            ("merchant", "merchant"),
            " cartão ",
            ("card_last4", "card_last4"),
        ],
        [
            "preciso que devolvam ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " cobrados por ",
            ("merchant", "merchant"),
            " abram reclamacao",
        ],
        [
            "Por favor iniciem o processo de chargeback da transação na ",
            ("merchant", "merchant"),
            " em ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "Contestação formal da cobrança indevida de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " no estabelecimento ",
            ("merchant", "merchant"),
        ],
        [
            "quero recorrer da cobranca na ",
            ("merchant", "merchant"),
            " de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
        ],
        [
            "Desejo abrir uma disputa comercial no valor de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " referente à ",
            ("merchant", "merchant"),
        ],
        [
            "Abrir estorno para a compra na ",
            ("merchant", "merchant"),
            " de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
        ],
        [
            "solicito disputa do valor de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " na ",
            ("merchant", "merchant"),
            " efetuado em ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "Quero solicitar o estorno do pagamento de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " na ",
            ("merchant", "merchant"),
        ],
        [
            "Abro reclamação por cobrança errada de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " na ",
            ("merchant", "merchant"),
        ],
        [
            "contestar compra no ",
            ("merchant", "merchant"),
            " cartao final ",
            ("card_last4", "card_last4"),
        ],
        [
            "Exijo abertura de processo de disputa pelo lançamento de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " da ",
            ("merchant", "merchant"),
        ],
        [
            "Desejo contestar e reaver o valor de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " pago à ",
            ("merchant", "merchant"),
        ],
        [
            "gostaria de abrir contestacao para ",
            ("merchant", "merchant"),
            " no total de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
        ],
        [
            "Reclamar devolução do débito na ",
            ("merchant", "merchant"),
            " de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
        ],
        [
            "Por favor encaminhem a disputa da cobrança de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " na ",
            ("merchant", "merchant"),
            " cartão ",
            ("card_last4", "card_last4"),
        ],
    ],
    "request_human_agent": [
        ["Quero falar com um atendente"],
        ["Me passa para uma pessoa"],
        ["Preciso de um atendente humano"],
        ["Não quero falar com o robô"],
        ["Transfira para um especialista"],
        ["Falar com humano por favor"],
        ["Quero falar com uma pessoa de verdade"],
        ["Pode me transferir para um operador?"],
        ["Atendente humano por favor"],
        ["Preciso falar com alguém do suporte"],
        ["Não entendi a resposta quero suporte humano"],
        ["Me transfere para atendimento pessoal"],
        ["Por favor me encaminhe para um atendente"],
        ["Quero suporte com um funcionário"],
        ["Robô não resolve passa para um humano"],
        ["Atendimento humano urgente"],
        ["Gostaria de falar com um representante da central"],
        ["Falar com suporte humano"],
        ["Conectar com atendente disponível"],
        ["Transferência para um operador humano por favor"],
        ["Quero assistência de uma pessoa real"],
        ["Me conecta com alguém da equipe"],
        ["Preciso de ajuda de um profissional humano"],
        ["Passa para o atendente"],
        ["Não quero falar com máquina"],
        ["Chama um atendente por favor"],
        ["Atendimento com consultor humano"],
        ["Quero falar com alguém da gerência"],
        ["Encaminhar para suporte técnico humano"],
        ["Operador de atendimento por favor"],
        ["Poderia falar com um especialista humano?"],
        ["Quero uma pessoa de carne e osso"],
        ["Me passe para a central humana"],
        ["Preciso conversar com um humano"],
        ["Robô não me ajuda quero uma pessoa"],
        ["Transfere essa conversa para um operador"],
        ["Quero atendimento com atendente real"],
        ["Solicito contato com equipe humana"],
        ["Atendimento pessoal por favor"],
        ["Gostaria de falar com um atendente agora"],
    ],
    "provide_identity_data": [
        [
            "Meu nome é ",
            ("full_name", "full_name"),
            ", documento ",
            ("document_type", "document_type"),
            " número ",
            ("document_number", "document_number"),
        ],
        [
            "Sou ",
            ("full_name", "full_name"),
            ", meu documento é ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            " e email ",
            ("email", "email"),
        ],
        [
            "meu nome ",
            ("full_name", "full_name"),
            " data de nascimento ",
            ("birth_date", "birth_date"),
            " telefone ",
            ("phone", "phone"),
        ],
        [
            "Dados pessoais: nome ",
            ("full_name", "full_name"),
            ", ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", telefone ",
            ("phone", "phone"),
        ],
        [
            "ola me chamo ",
            ("full_name", "full_name"),
            " meu email e ",
            ("email", "email"),
            " e nasci em ",
            ("birth_date", "birth_date"),
        ],
        [
            "Para verificação: titular ",
            ("full_name", "full_name"),
            ", ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", nascido em ",
            ("birth_date", "birth_date"),
        ],
        [
            "Confirmo meus dados: ",
            ("full_name", "full_name"),
            ", celular ",
            ("phone", "phone"),
            ", email ",
            ("email", "email"),
        ],
        [
            "meu documento e ",
            ("document_type", "document_type"),
            " numero ",
            ("document_number", "document_number"),
            " em nome de ",
            ("full_name", "full_name"),
        ],
        [
            "Dados cadastrais: titular ",
            ("full_name", "full_name"),
            ", cartão ",
            ("card_number", "card_number"),
            ", email ",
            ("email", "email"),
        ],
        [
            "Cadastro: ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", telefone ",
            ("phone", "phone"),
            ", nascimento ",
            ("birth_date", "birth_date"),
        ],
        [
            "Me identifico como ",
            ("full_name", "full_name"),
            ", ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
        ],
        [
            "Aqui meus dados para conferência: ",
            ("full_name", "full_name"),
            " e documento ",
            ("document_number", "document_number"),
        ],
        [
            "nome completo ",
            ("full_name", "full_name"),
            ", tipo ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", email ",
            ("email", "email"),
        ],
        [
            "Sou o titular ",
            ("full_name", "full_name"),
            ", data ",
            ("birth_date", "birth_date"),
            ", contato ",
            ("phone", "phone"),
        ],
        [
            "documento ",
            ("document_type", "document_type"),
            " sob número ",
            ("document_number", "document_number"),
            " de ",
            ("full_name", "full_name"),
        ],
        [
            "informacoes: ",
            ("full_name", "full_name"),
            ", ",
            ("email", "email"),
            ", ",
            ("phone", "phone"),
            ", ",
            ("document_number", "document_number"),
        ],
        [
            "Titular do cartão: ",
            ("full_name", "full_name"),
            ", tipo de doc ",
            ("document_type", "document_type"),
            ", número ",
            ("document_number", "document_number"),
        ],
        [
            "ola sou ",
            ("full_name", "full_name"),
            ", meu cartao e ",
            ("card_number", "card_number"),
            " e email ",
            ("email", "email"),
        ],
        [
            "Identificação: ",
            ("full_name", "full_name"),
            ", data de nascimento ",
            ("birth_date", "birth_date"),
            ", doc ",
            ("document_number", "document_number"),
        ],
        [
            "Envio meus dados de identificação: ",
            ("full_name", "full_name"),
            ", ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", telefone ",
            ("phone", "phone"),
        ],
    ],
    "provide_otp_code": [
        ["O código que recebi por SMS é ", ("otp_code", "otp_code")],
        ["Meu token de confirmação é ", ("otp_code", "otp_code")],
        ["o codigo otp e ", ("otp_code", "otp_code")],
        ["Acabei de receber o código: ", ("otp_code", "otp_code")],
        ["Digite o código ", ("otp_code", "otp_code"), " que chegou no meu celular"],
        ["codigo de verificacao: ", ("otp_code", "otp_code")],
        ["O token recebido é ", ("otp_code", "otp_code")],
        ["Aqui está o código que chegou: ", ("otp_code", "otp_code")],
        ["Pronto, meu código de segurança é ", ("otp_code", "otp_code")],
        ["o codigo que recebi no sms e ", ("otp_code", "otp_code"), " confirmar"],
        ["Meu código de autorização é ", ("otp_code", "otp_code")],
        ["Chave de segurança recebida: ", ("otp_code", "otp_code")],
        ["ja recebi o token sms ", ("otp_code", "otp_code")],
        ["O código OTP que chegou foi ", ("otp_code", "otp_code")],
        ["Confirmo a operação com o código ", ("otp_code", "otp_code")],
        ["meu codigo e ", ("otp_code", "otp_code")],
        ["Token de verificação: ", ("otp_code", "otp_code")],
        ["O código temporário enviado é ", ("otp_code", "otp_code")],
        ["chave dinamica ", ("otp_code", "otp_code")],
        ["Informo o código de validação recebido: ", ("otp_code", "otp_code")],
    ],
    "confirm": [
        ["Sim"],
        ["Sim confirmo"],
        ["Com certeza"],
        ["Correto"],
        ["De acordo"],
        ["Sim pode bloquear"],
        ["Confirmado com certeza"],
        ["Sim pode prosseguir"],
        ["Exatamente"],
        ["Sim por favor"],
        ["Isso mesmo"],
        ["Sim autorizo"],
        ["Positivo"],
        ["Sim estou de acordo"],
        ["Pode continuar"],
        ["Sim confirmo a solicitacao"],
        ["Correto pode fazer"],
        ["Sim desejo prosseguir"],
        ["Sim confirmo os dados"],
        ["Perfeito pode executar"],
        ["Sim confirmo tudo"],
        ["Com certeza faca isso"],
        ["Sim pode cancelar"],
        ["Correto e isso"],
        ["Autorizado"],
        ["Sim proceda com o processo"],
        ["Confirmadissimo"],
        ["Sim confirmo a operacao"],
        ["Sim esta correto"],
        ["Pode seguir em frente"],
        ["Sim claro"],
        ["Sim concordo"],
        ["Exato pode continuar"],
        ["Sim aceito"],
        ["Correto por favor"],
        ["Sim pode dar andamento"],
        ["Afirmativo pode prosseguir"],
        ["Sim eu confirmo"],
        ["Com certeza pode seguir"],
        ["Sim faca o bloqueio"],
    ],
    "deny": [
        ["Não"],
        ["Não quero"],
        ["Cancelar agora"],
        ["Não autorizo"],
        ["Negativo não quero"],
        ["De jeito nenhum"],
        ["Não cancelar"],
        ["Não concordo"],
        ["Não pode parar"],
        ["Não não faça isso"],
        ["Não recuso"],
        ["Cancelar operacao"],
        ["Não não é isso"],
        ["De forma alguma"],
        ["Não pare o processo"],
        ["Não quero continuar"],
        ["Não abortar"],
        ["Cancela por favor"],
        ["Não discordo"],
        ["Não de jeito nenhum"],
        ["Não estou de acordo"],
        ["Não deixe como está"],
        ["Cancelar tudo"],
        ["Não não autorizo"],
        ["Negativo cancelar"],
        ["Não quero prosseguir"],
        ["Não descarto"],
        ["Não nao faca"],
        ["Cancelar solicitacao"],
        ["Não não confirmo"],
        ["Não para"],
        ["Não nada disso"],
        ["Não me arrependi"],
        ["Não interromper"],
        ["Recuso essa opção"],
        ["Não não desejo"],
        ["Não espere"],
        ["Cancelar esse pedido"],
        ["Não prefiro não"],
        ["Não não reconheço"],
    ],
    "check_balance": [
        [
            "Qual é o saldo disponível no meu cartão final ",
            ("card_last4", "card_last4"),
            "?",
        ],
        ["Gostaria de consultar o saldo da minha conta"],
        ["saldo do cartao ", ("card_last4", "card_last4"), " por favor"],
        [
            "Boa tarde, vocês podem informar o saldo do cartão final ",
            ("card_last4", "card_last4"),
            "?",
        ],
        ["quanto tenho de saldo no cartao ", ("card_last4", "card_last4")],
        [
            "Qual é o limite disponível no cartão com terminação ",
            ("card_last4", "card_last4"),
            "?",
        ],
        ["Quero saber quanto dinheiro tenho no cartão ", ("card_last4", "card_last4")],
        ["saldo disponivel no meu cartao ", ("card_last4", "card_last4")],
        [
            "Por favor informem o saldo da conta vinculada ao cartão ",
            ("card_last4", "card_last4"),
        ],
        ["Consulta de saldo disponível no cartão ", ("card_last4", "card_last4")],
        ["Quanto crédito ainda tenho no cartão ", ("card_last4", "card_last4"), "?"],
        ["quero saber meu saldo atual no cartao ", ("card_last4", "card_last4")],
        ["Consultar saldo da conta e do cartão ", ("card_last4", "card_last4")],
        [
            "Qual o saldo atual do meu plástico terminado em ",
            ("card_last4", "card_last4"),
            "?",
        ],
        ["saldo e limite do cartao ", ("card_last4", "card_last4"), " por favor"],
        [
            "Desejo verificar quanto posso gastar no cartão ",
            ("card_last4", "card_last4"),
        ],
        ["Informações de saldo do meu cartão ", ("card_last4", "card_last4")],
        ["podem me dizer meu saldo no cartao ", ("card_last4", "card_last4")],
        ["Quanto resta de limite no cartão final ", ("card_last4", "card_last4"), "?"],
        ["Ver saldo atual do cartão de débito ", ("card_last4", "card_last4")],
    ],
    "check_recent_transactions": [
        [
            "Quero ver as últimas transações do meu cartão final ",
            ("card_last4", "card_last4"),
        ],
        ["Pode listar as últimas compras da minha fatura?"],
        ["ver ultimos lancamentos do cartao ", ("card_last4", "card_last4")],
        [
            "Boa tarde, gostaria de consultar o extrato de compras do cartão ",
            ("card_last4", "card_last4"),
        ],
        ["ultimas transacoes do cartao ", ("card_last4", "card_last4"), " por favor"],
        [
            "Por favor listar as compras recentes feitas com o cartão final ",
            ("card_last4", "card_last4"),
        ],
        [
            "Quais foram os gastos recentes no meu cartão ",
            ("card_last4", "card_last4"),
            "?",
        ],
        ["mostrar extrato recente do meu cartao ", ("card_last4", "card_last4")],
        [
            "Desejo consultar os últimos lançamentos do cartão ",
            ("card_last4", "card_last4"),
        ],
        ["Histórico de transações do cartão com final ", ("card_last4", "card_last4")],
        [
            "Quais são as compras recentes faturadas no cartão ",
            ("card_last4", "card_last4"),
            "?",
        ],
        ["listar compras recentes do cartao ", ("card_last4", "card_last4")],
        [
            "Gostaria de ver as movimentações desta semana no cartão ",
            ("card_last4", "card_last4"),
        ],
        ["extrato detalhado do cartao ", ("card_last4", "card_last4")],
        [
            "Quais pagamentos foram processados no cartão final ",
            ("card_last4", "card_last4"),
            " ultimamente?",
        ],
        [
            "Movimentações recentes no cartão de débito terminado em ",
            ("card_last4", "card_last4"),
        ],
        ["mostrem as ultimas compras do cartao ", ("card_last4", "card_last4")],
        [
            "Desejo visualizar os débitos recentes do cartão ",
            ("card_last4", "card_last4"),
        ],
        [
            "Consultar histórico recente de pagamentos no cartão ",
            ("card_last4", "card_last4"),
        ],
        [
            "Quero verificar os últimos lançamentos do cartão final ",
            ("card_last4", "card_last4"),
        ],
    ],
    "greeting": [
        ["Olá"],
        ["Bom dia"],
        ["Boa tarde"],
        ["Boa noite"],
        ["Oi tudo bem"],
        ["Olá bom dia"],
        ["Oi preciso de ajuda"],
        ["Olá gostaria de tirar uma dúvida"],
        ["Opa tudo bem"],
        ["Oi oi"],
        ["Olá equipe de suporte"],
        ["Bom dia a todos"],
        ["Boa tarde equipe"],
        ["Oi pessoal"],
        ["Olá como vai você"],
        ["Oi gostaria de uma informação"],
        ["Boa tarde preciso de atendimento"],
        ["Oi bom dia"],
        ["Olá tudo joia"],
        ["E aí tudo bem"],
        ["Saudações cordiais"],
        ["Oi tudo certo"],
        ["Bom dia atendimento"],
        ["Olá gostaria de falar com vocês"],
        ["Boa tarde como vai"],
        ["Olá início de atendimento"],
        ["Oi tenho uma pergunta"],
        ["Olá boa noite suporte"],
        ["Oi bom dia por favor"],
        ["Opa boa tarde"],
        ["Olá equipe"],
        ["Oi tudo bem por aí"],
        ["Bom dia suporte ao cliente"],
        ["Olá preciso de um auxílio"],
        ["Boa tarde gostaria de ajuda"],
        ["Oi queria tirar uma duvida"],
        ["Olá contato com o banco"],
        ["Oi oi boa tarde"],
        ["Bom dia como vocês estão"],
        ["Olá atendimento ao consumidor"],
    ],
    "out_of_scope": [
        ["Qual é a receita de bolo de cenoura?"],
        ["Como está o tempo em São Paulo hoje?"],
        ["Quem ganhou a copa do mundo de 2002?"],
        ["Me conta uma piada engraçada"],
        ["Qual é a capital do Canadá?"],
        ["Recomende um bom filme de ação"],
        ["Quanto custa uma passagem para Tóquio?"],
        ["Como consertar um pneu furado?"],
        ["Quem pintou o teto da Capela Sistina?"],
        ["Escreva um poema sobre flores"],
        ["Que horas são em Londres agora?"],
        ["Como fazer um bom café expresso?"],
        ["Quantos planetas existem no sistema solar?"],
        ["Me ajude com a lição de casa de história"],
        ["Como aprender a falar inglês rápido?"],
        ["Por que o mar é azul?"],
        ["Quem descobriu o Brasil em 1500?"],
        ["Quais são as melhores músicas do momento?"],
        ["Traduza esta frase para o italiano"],
        ["Qual é o melhor restaurante de massas?"],
        ["Como cuidar de uma planta dentro de casa?"],
        ["Qual a velocidade máxima de um guepardo?"],
        ["Como trocar a lâmpada do carro?"],
        ["Quem foi Albert Einstein?"],
        ["Qual é a montanha mais alta do Brasil?"],
        ["Dicas para fazer caminhada e emagrecer"],
        ["Como fazer pão de queijo caseiro?"],
        ["Como funciona um painel de energia solar?"],
        ["Qual o livro mais lido do mundo?"],
        ["Que roupa usar em dia de chuva?"],
        ["Como plantar temperos em apartamento?"],
        ["Quem inventou a lâmpada elétrica?"],
        ["Qual é o maior oceano da Terra?"],
        ["Como afinar um violão?"],
        ["Quais filmes estão passando no cinema?"],
        ["Qual a distância da Terra até a Lua?"],
        ["Como escrever uma redação para concurso?"],
        ["Por que as folhas caem no outono?"],
        ["Qual a moeda oficial do Japão?"],
        ["Como fazer pizza em casa?"],
    ],
}

VAL_TEMPLATES: dict[str, list[Template]] = {
    "report_unrecognized_charge": [
        [
            "Desconheço totalmente uma transação de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " na ",
            ("merchant", "merchant"),
            " no cartão ",
            ("card_last4", "card_last4"),
        ],
        [
            "Cobraram ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " da ",
            ("merchant", "merchant"),
            " mas não reconheço essa compra",
        ],
        [
            "Na fatura consta um débito indevido de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " em ",
            ("merchant", "merchant"),
            " no dia ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "vejo um pagamento estranho de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " na ",
            ("merchant", "merchant"),
            " no cartao ",
            ("card_last4", "card_last4"),
        ],
        [
            "Prezado suporte, desconheço um lançamento de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " feito em ",
            ("merchant", "merchant"),
        ],
        [
            "Não autorizei o débito de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " efetuado na ",
            ("merchant", "merchant"),
            " cartão ",
            ("card_last4", "card_last4"),
        ],
        [
            "Apareceu um gasto não identificado em ",
            ("merchant", "merchant"),
            " de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
        ],
        [
            "Cobrança atípica de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " em ",
            ("merchant", "merchant"),
            " na data de ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "nao faco ideia de quem comprou na ",
            ("merchant", "merchant"),
            " por ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
        ],
        [
            "Identifico lançamento fraudulento de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " no ",
            ("merchant", "merchant"),
            " cartão ",
            ("card_last4", "card_last4"),
        ],
    ],
    "report_lost_card": [
        [
            "Extraviei meu cartão de débito terminado em ",
            ("card_last4", "card_last4"),
            " hoje de manhã",
        ],
        [
            "Não consigo achar meu cartão final ",
            ("card_last4", "card_last4"),
            ", acho que caiu na rua",
        ],
        ["perdi o cartao ", ("card_last4", "card_last4"), " e preciso registrar"],
        [
            "Esqueci onde deixei meu cartão com final ",
            ("card_last4", "card_last4"),
            " e sumiu",
        ],
        [
            "Comunicação de extravio de cartão com dígitos finais ",
            ("card_last4", "card_last4"),
        ],
        [
            "Perdi meu cartão final ",
            ("card_last4", "card_last4"),
            " dentro do aeroporto",
        ],
        [
            "Deixei meu cartão terminado em ",
            ("card_last4", "card_last4"),
            " em uma loja",
        ],
        [
            "perdi meu cartao de credito ",
            ("card_number", "card_number"),
            " recentemente",
        ],
        [
            "Não sei do paradeiro do meu cartão final ",
            ("card_last4", "card_last4"),
            ", foi perdido",
        ],
        [
            "Perda involuntária do cartão com terminação ",
            ("card_last4", "card_last4"),
            " no transporte",
        ],
    ],
    "report_stolen_card": [
        [
            "Fui vítima de assalto hoje e levaram meu cartão de débito ",
            ("card_last4", "card_last4"),
        ],
        [
            "Tiraram meu cartão final ",
            ("card_last4", "card_last4"),
            " da minha mochila",
        ],
        ["roubaram meu cartao final ", ("card_last4", "card_last4"), " me ajudem"],
        [
            "Sofri um furto do meu cartão terminado em ",
            ("card_last4", "card_last4"),
            " no ônibus",
        ],
        [
            "Aviso urgente: levaram meu cartão final ",
            ("card_last4", "card_last4"),
            " em um assalto",
        ],
        ["Fui roubado na rua e perdi a posse do cartão ", ("card_last4", "card_last4")],
        [
            "Levaram minha bolsa com o cartão terminado em ",
            ("card_last4", "card_last4"),
            " no restaurante",
        ],
        ["furto do cartao numero ", ("card_number", "card_number"), " durante a tarde"],
        [
            "Acabaram de roubar meus documentos e o cartão ",
            ("card_last4", "card_last4"),
        ],
        [
            "Registro de roubo qualificado do cartão terminado em ",
            ("card_last4", "card_last4"),
        ],
    ],
    "report_suspicious_activity": [
        [
            "Notei atividade suspeita no cartão ",
            ("card_last4", "card_last4"),
            " com alertas preventivos de segurança",
        ],
        [
            "Recebi alerta de tentativa de login não autorizado no Internet Banking",
        ],
        [
            "aviso de acesso suspeito detectado no dia ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "Suspeito que estão tentando clonar meu cartão ",
            ("card_last4", "card_last4"),
        ],
        [
            "Comunicação de segurança sobre links falsos e tentativa de golpe",
        ],
        [
            "Atividade suspeita detectada: recebi um token SMS sem ter solicitado",
        ],
        [
            "acho que meu cartao ",
            ("card_last4", "card_last4"),
            " foi clonado num caixa suspeito",
        ],
        [
            "Tentativa estranha de alteração cadastral que não realizei",
        ],
        [
            "Registro preventivo de possível fraude no cartão ",
            ("card_last4", "card_last4"),
        ],
        [
            "Alerta sobre tentativas de login a partir de endereço desconhecido",
        ],
    ],
    "request_card_block": [
        [
            "Por favor desativem imediatamente meu cartão final ",
            ("card_last4", "card_last4"),
        ],
        [
            "Preciso bloquear meu cartão de débito terminado em ",
            ("card_last4", "card_last4"),
            " com urgência",
        ],
        ["bloquear cartao ", ("card_last4", "card_last4"), " o quanto antes"],
        [
            "Solicito o congelamento imediato do meu cartão final ",
            ("card_last4", "card_last4"),
        ],
        [
            "Procedam com o bloqueio do meu cartão de final ",
            ("card_last4", "card_last4"),
        ],
        [
            "Quero inativar imediatamente meu cartão de número ",
            ("card_number", "card_number"),
        ],
        ["por favor bloqueiem logo, cartao final ", ("card_last4", "card_last4")],
        ["Aplicar trava total no cartão final ", ("card_last4", "card_last4")],
        [
            "Quero suspender todas as operações do meu cartão ",
            ("card_last4", "card_last4"),
        ],
        ["Bloqueio urgente do cartão com terminação ", ("card_last4", "card_last4")],
    ],
    "request_dispute": [
        [
            "Venho solicitar um estorno formal de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " cobrado na ",
            ("merchant", "merchant"),
        ],
        [
            "Desejo contestar a transação de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " na ",
            ("merchant", "merchant"),
            " em ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "abrir disputa de compra na ",
            ("merchant", "merchant"),
            " por ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
        ],
        [
            "Exijo o reembolso e cancelamento da cobrança de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " da ",
            ("merchant", "merchant"),
        ],
        [
            "Por favor iniciem a contestação da compra na ",
            ("merchant", "merchant"),
            " cartão ",
            ("card_last4", "card_last4"),
        ],
        [
            "Quero abrir processo formal de disputa para ",
            ("merchant", "merchant"),
            " no valor de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
        ],
        [
            "Pedido de estorno para o débito de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " em ",
            ("merchant", "merchant"),
        ],
        [
            "Contesto o pagamento na ",
            ("merchant", "merchant"),
            " no valor de ",
            ("currency", "currency"),
            " ",
            ("amount", "amount"),
            " do dia ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "solicitacao de chargeback para a compra na ",
            ("merchant", "merchant"),
            " de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
        ],
        [
            "Reclamação para devolução de valor cobrado na ",
            ("merchant", "merchant"),
            " cartão ",
            ("card_last4", "card_last4"),
        ],
    ],
    "request_human_agent": [
        ["Por favor me transfira para um atendente da central"],
        ["Quero conversar diretamente com uma pessoa"],
        ["Solicito falar com um operador humano disponível"],
        ["Me conecte a um atendente real por favor"],
        ["Encaminhar esta sessão para atendimento humano"],
        ["Preciso do suporte de um atendente humano agora"],
        ["Não consigo resolver com o bot me transfira"],
        ["Quero ser atendido por uma pessoa da equipe"],
        ["Por gentileza passe a ligação para um consultor"],
        ["Favor transferir para equipe de atendimento humana"],
    ],
    "provide_identity_data": [
        [
            "Confirmação de titularidade: me chamo ",
            ("full_name", "full_name"),
            ", ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", email ",
            ("email", "email"),
        ],
        [
            "Meus dados são ",
            ("full_name", "full_name"),
            ", nascido em ",
            ("birth_date", "birth_date"),
            " e celular ",
            ("phone", "phone"),
        ],
        [
            "aqui meus dados ",
            ("full_name", "full_name"),
            " documento ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
        ],
        [
            "Nome do cliente ",
            ("full_name", "full_name"),
            ", telefone ",
            ("phone", "phone"),
            ", documento ",
            ("document_number", "document_number"),
        ],
        [
            "Envio meu ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", email ",
            ("email", "email"),
            " e data ",
            ("birth_date", "birth_date"),
        ],
        [
            "Titular ",
            ("full_name", "full_name"),
            ", cartão ",
            ("card_number", "card_number"),
            ", contato ",
            ("phone", "phone"),
        ],
        [
            "identificacao ",
            ("full_name", "full_name"),
            " com doc ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            " e email ",
            ("email", "email"),
        ],
        [
            "Dados do titular da conta: ",
            ("full_name", "full_name"),
            ", nascimento ",
            ("birth_date", "birth_date"),
            ", doc ",
            ("document_number", "document_number"),
        ],
        [
            "Registro cadastral: ",
            ("full_name", "full_name"),
            ", ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", celular ",
            ("phone", "phone"),
        ],
        [
            "Identificação para validação: ",
            ("full_name", "full_name"),
            ", data de nascimento ",
            ("birth_date", "birth_date"),
            ", email ",
            ("email", "email"),
        ],
    ],
    "provide_otp_code": [
        ["O número de confirmação recebido por SMS foi ", ("otp_code", "otp_code")],
        ["Meu código OTP para liberar a transação é ", ("otp_code", "otp_code")],
        ["ja chegou o codigo otp ", ("otp_code", "otp_code")],
        ["Envio o código de validação temporário: ", ("otp_code", "otp_code")],
        ["Código de segurança recebido no meu telefone: ", ("otp_code", "otp_code")],
        ["O código enviado por SMS para mim é ", ("otp_code", "otp_code")],
        ["Token dinâmico recebido no celular: ", ("otp_code", "otp_code")],
        ["segue o codigo otp ", ("otp_code", "otp_code")],
        ["Digito o código temporário ", ("otp_code", "otp_code"), " solicitado"],
        ["Chave de confirmação por SMS: ", ("otp_code", "otp_code")],
    ],
    "confirm": [
        ["Com certeza confirmo"],
        ["Sim estou de pleno acordo"],
        ["Pode prosseguir com a operação"],
        ["Sim é exatamente isso"],
        ["Confirmo todas as informações"],
        ["Sim por favor continue"],
        ["Sim confirmo essa solicitação"],
        ["Correto prossiga agora"],
        ["Aceito e autorizo"],
        ["Sim totalmente confirmado"],
    ],
    "deny": [
        ["Não recuso o procedimento"],
        ["Não cancele imediatamente"],
        ["Cancelar não quero prosseguir"],
        ["Não discordo totalmente disso"],
        ["Não anule a solicitação"],
        ["Não cancelem por favor"],
        ["Não com certeza não"],
        ["Não descarto essa opção"],
        ["Não desautorizo"],
        ["Não não quero que prossiga"],
    ],
    "check_balance": [
        [
            "Poderia me informar o saldo disponível no cartão com final ",
            ("card_last4", "card_last4"),
            "?",
        ],
        [
            "Gostaria de verificar o valor disponível no meu cartão ",
            ("card_last4", "card_last4"),
        ],
        ["consultar saldo do cartao ", ("card_last4", "card_last4"), " agora"],
        [
            "Qual é o saldo total restante no meu cartão final ",
            ("card_last4", "card_last4"),
            "?",
        ],
        [
            "Quero checar quanto limite ainda tenho no cartão ",
            ("card_last4", "card_last4"),
        ],
        [
            "Por gentileza me informem o saldo do meu cartão ",
            ("card_last4", "card_last4"),
        ],
        ["quanto tenho disponível no cartão final ", ("card_last4", "card_last4")],
        [
            "Solicitação de verificação de saldo da conta do cartão ",
            ("card_last4", "card_last4"),
        ],
        [
            "Qual a quantia disponível no meu plástico com final ",
            ("card_last4", "card_last4"),
            "?",
        ],
        [
            "Consultar fundos disponíveis no cartão débito ",
            ("card_last4", "card_last4"),
        ],
    ],
    "check_recent_transactions": [
        [
            "Poderiam detalhar as compras mais recentes no cartão final ",
            ("card_last4", "card_last4"),
            "?",
        ],
        [
            "Quisera consultar as compras desta semana no cartão ",
            ("card_last4", "card_last4"),
        ],
        ["ver historico de ultimas compras no cartao ", ("card_last4", "card_last4")],
        [
            "Por favor mostrem os lançamentos recentes do cartão terminado em ",
            ("card_last4", "card_last4"),
        ],
        [
            "Desejo checar o extrato detalhado do meu cartão ",
            ("card_last4", "card_last4"),
        ],
        [
            "Quais valores foram debitados recentemente no cartão ",
            ("card_last4", "card_last4"),
            "?",
        ],
        [
            "Conferência de transações dos últimos dias no cartão ",
            ("card_last4", "card_last4"),
        ],
        [
            "mostrem os lancamentos do cartao ",
            ("card_last4", "card_last4"),
            " deste mes",
        ],
        [
            "Extrato de débitos e compras recentes do cartão ",
            ("card_last4", "card_last4"),
        ],
        ["Lista de compras aprovadas no meu cartão ", ("card_last4", "card_last4")],
    ],
    "greeting": [
        ["Olá bom dia a todos"],
        ["Muito boa tarde"],
        ["Olá um abraço para a equipe"],
        ["Boa tarde pessoal do banco"],
        ["Oi tenho algumas dúvidas sobre o app"],
        ["Bom dia desejo fazer uma consulta"],
        ["Olá boa tarde gostaria de uma orientação"],
        ["Boa noite prezada equipe"],
        ["Olá como vocês estão"],
        ["Saudações à equipe de atendimento ao cliente"],
    ],
    "out_of_scope": [
        ["Qual é o maior rio do mundo em extensão?"],
        ["Como preparar sushi tradicional em casa?"],
        ["Quem escreveu Dom Casmurro?"],
        ["Qual a distância entre Marte e a Terra?"],
        ["Como cuidar de orquídeas e suculentas?"],
        ["Qual é a capital da Austrália?"],
        ["Como aprender a tocar teclado sozinho?"],
        ["Quem inventou o avião Santos Dumont ou os irmãos Wright?"],
        ["Por que ocorrem os eclipses solares?"],
        ["Dicas de yoga para iniciantes"],
    ],
}
