"""Spanish templates for intent and slot generation.

Contains:
- 15 intents
- 40 train templates/phrases per intent
- 10 validation templates/phrases per intent (strictly disjoint from train)
- Varied linguistic registers, casing, colloquialisms, and common typos.
"""

# Type alias: a template is a list where each element is either a literal string
# or a tuple of (slot_type, filler_key).
Template = list[str | tuple[str, str]]

TRAIN_TEMPLATES: dict[str, list[Template]] = {
    "report_unrecognized_charge": [
        [
            "No reconozco un cargo de ",
            ("currency", "currency"),
            ("amount", "amount"),
            " en ",
            ("merchant", "merchant"),
            " en mi tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "Aparece un cobro de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " en ",
            ("merchant", "merchant"),
            " que yo no realicé",
        ],
        [
            "Veo una compra sospechosa de ",
            ("currency", "currency"),
            ("amount", "amount"),
            " en ",
            ("merchant", "merchant"),
            " con fecha ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "hola desconosco un cobro en ",
            ("merchant", "merchant"),
            " de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
        ],
        [
            "URGENTE: cargo no reconocido de ",
            ("currency", "currency"),
            ("amount", "amount"),
            " en ",
            ("merchant", "merchant"),
            " en tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "Hay una transacción extraña en ",
            ("merchant", "merchant"),
            " por ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " el ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "me descontaron ",
            ("currency", "currency"),
            ("amount", "amount"),
            " de ",
            ("merchant", "merchant"),
            " y yo no compre nada",
        ],
        [
            "Desconozco el pago de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " a ",
            ("merchant", "merchant"),
            " en mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
        ],
        [
            "Reporto una compra fraudulenta en ",
            ("merchant", "merchant"),
            " por ",
            ("currency", "currency"),
            ("amount", "amount"),
        ],
        [
            "tengo un debito desconocido en mi tarjeta ",
            ("card_last4", "card_last4"),
            " de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " en ",
            ("merchant", "merchant"),
        ],
        [
            "No autoricé el consumo de ",
            ("currency", "currency"),
            ("amount", "amount"),
            " en ",
            ("merchant", "merchant"),
            " realizado ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "Alguien usó mi tarjeta ",
            ("card_last4", "card_last4"),
            " en ",
            ("merchant", "merchant"),
            " por valor de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
        ],
        [
            "veo en mi extracto un gasto de ",
            ("currency", "currency"),
            ("amount", "amount"),
            " en ",
            ("merchant", "merchant"),
            " que no es mio",
        ],
        [
            "Aparece una compra de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " en ",
            ("merchant", "merchant"),
            " con mi plástico ",
            ("card_last4", "card_last4"),
        ],
        [
            "desconosco cobro en ",
            ("merchant", "merchant"),
            " de fecha ",
            ("transaction_date", "transaction_date"),
            " por ",
            ("currency", "currency"),
            ("amount", "amount"),
        ],
        [
            "Cobro no identificado de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " en ",
            ("merchant", "merchant"),
            " tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "Quiero reportar un cargo no reconocido en ",
            ("merchant", "merchant"),
            " por ",
            ("currency", "currency"),
            ("amount", "amount"),
        ],
        [
            "No recuerdo haber comprado en ",
            ("merchant", "merchant"),
            " por ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " el ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "figura un cargo raro en ",
            ("merchant", "merchant"),
            " de ",
            ("currency", "currency"),
            ("amount", "amount"),
        ],
        [
            "Tengo un cobro indebido en ",
            ("merchant", "merchant"),
            " por ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " en la tarjeta ",
            ("card_last4", "card_last4"),
        ],
    ],
    "report_lost_card": [
        [
            "Perdí mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            " en el centro comercial",
        ],
        [
            "Se me extravió mi tarjeta ",
            ("card_last4", "card_last4"),
            " y no la encuentro",
        ],
        [
            "creo que perdi mi plastico ",
            ("card_last4", "card_last4"),
            " en un taxi ayer",
        ],
        [
            "URGENTE: extravié mi tarjeta de crédito número ",
            ("card_number", "card_number"),
        ],
        [
            "No encuentro mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            " por ninguna parte",
        ],
        [
            "hola perdi mi tarjeta ",
            ("card_last4", "card_last4"),
            " como hago para reportarla",
        ],
        [
            "Dejé olvidada mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            " en un restaurante",
        ],
        [
            "He perdido mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            " durante un viaje",
        ],
        [
            "se me perdio el plastico terminado en ",
            ("card_last4", "card_last4"),
            " hace unas horas",
        ],
        [
            "Buenas tardes, reporto la pérdida de mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
        ],
        [
            "Extravío de tarjeta: no sé dónde dejé mi tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "se me extravio la tarjeta ",
            ("card_last4", "card_last4"),
            " por favor ayudenme",
        ],
        [
            "Perdí mi billetera donde tenía la tarjeta ",
            ("card_last4", "card_last4"),
            ", se me cayó",
        ],
        [
            "Dejé mi tarjeta ",
            ("card_last4", "card_last4"),
            " en un cajero y ya no está",
        ],
        ["hola reporte de perdida de tarjeta ", ("card_last4", "card_last4")],
        [
            "No hallo mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            " desde esta mañana",
        ],
        [
            "Perdí mi tarjeta de débito ",
            ("card_number", "card_number"),
            " hace un rato",
        ],
        [
            "creo que deje mi tarjeta ",
            ("card_last4", "card_last4"),
            " en el supermercado",
        ],
        [
            "He extraviado mi tarjeta débito con terminación ",
            ("card_last4", "card_last4"),
        ],
        ["Reporto que perdí mi tarjeta con número ", ("card_number", "card_number")],
    ],
    "report_stolen_card": [
        [
            "Me robaron la billetera con mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
        ],
        [
            "Sufrí un asalto y se llevaron mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
        ],
        [
            "me acaban de robar mi tarjeta ",
            ("card_last4", "card_last4"),
            " en el metro",
        ],
        [
            "URGENTE: me hurtaron la tarjeta ",
            ("card_number", "card_number"),
            " hace unos minutos",
        ],
        [
            "Denuncio el robo de mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            " en la calle",
        ],
        ["robaron mi bolso donde tenia mi tarjeta ", ("card_last4", "card_last4")],
        [
            "Fui víctima de robo armado y me quitaron la tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "Me sustrajeron la tarjeta terminada en ",
            ("card_last4", "card_last4"),
            " de mi auto",
        ],
        ["hola me asaltaron y me quitaron la tarjeta ", ("card_last4", "card_last4")],
        [
            "Reporto que me sustrajeron mi tarjeta ",
            ("card_last4", "card_last4"),
            " con violencia",
        ],
        [
            "Unos sujetos me asaltaron y se llevaron mi plástico ",
            ("card_last4", "card_last4"),
        ],
        [
            "hurto de tarjeta terminada en ",
            ("card_last4", "card_last4"),
            " en el transporte público",
        ],
        [
            "Me abrieron la mochila y me robaron la tarjeta ",
            ("card_last4", "card_last4"),
        ],
        ["acaban de asaltarme, se llevaron la tarjeta ", ("card_last4", "card_last4")],
        [
            "Reporto el robo de mi tarjeta de crédito ",
            ("card_number", "card_number"),
            " hoy mismo",
        ],
        [
            "Me despojaron de mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            " en la estación",
        ],
        ["robo de tarjeta ", ("card_last4", "card_last4"), " en centro de la ciudad"],
        [
            "Me atracaron y perdí posesión de mi tarjeta ",
            ("card_last4", "card_last4"),
            " por robo",
        ],
        [
            "delincuentes se llevaron mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
        ],
        [
            "Sufro robo con violencia de tarjeta ",
            ("card_last4", "card_last4"),
            " hace media hora",
        ],
    ],
    "report_suspicious_activity": [
        [
            "Recibí un SMS alertando de acceso sospechoso a mi banca móvil",
        ],
        [
            "Hay actividad sospechosa en mi cuenta, intentos fallidos de login",
        ],
        [
            "me llego un sms sospechoso pidiendo confirmar mis datos de la tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "Alerta: veo intentos de conexión extraños en mi cuenta desde otro país",
        ],
        [
            "Detecto actividad inusual en mi banca en línea el día ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "recibí notificación de clave de seguridad que yo nunca pedí",
        ],
        [
            "Sospecho que intentaron clonar mi tarjeta ",
            ("card_last4", "card_last4"),
            " en un cajero",
        ],
        [
            "Múltiples alertas de código de verificación que no he solicitado",
        ],
        [
            "actividad rara en mi cuenta, alerta de cambio de contraseña no autorizado",
        ],
        [
            "Notifico intento de acceso no autorizado a mi perfil bancario",
        ],
        [
            "Aviso sospechoso: me llegó correo de phishing suplantando al banco",
        ],
        [
            "veo notificaciones de intentos fallidos de ingreso con mi usuario",
        ],
        [
            "Aviso de inicio de sesión no reconocido desde una IP desconocida",
        ],
        [
            "Intento sospechoso de acceso detectado el ",
            ("transaction_date", "transaction_date"),
            " en mi aplicación",
        ],
        [
            "alerta de seguridad por posible clonacion o skimming en mi tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "Bloqueo preventivo del sistema por actividad sospechosa en tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "Creo que intentan vulnerar mi cuenta con mensajes fraudulentos",
        ],
        [
            "Recibo mensajes sospechosos solicitando código de seguridad de tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "sospecha de fraude: detectaron intentos de desbloqueo de clave",
        ],
        [
            "Alertas de seguridad por intentos indebidos de ingreso a mi cuenta",
        ],
        [
            "Aviso urgente: alerta de inicio de sesión desde un teléfono desconocido",
        ],
        [
            "Intentan entrar a mi aplicación bancaria, avisos de clave errónea",
        ],
        [
            "sospecho de actividad fraudulenta en mi tarjeta ",
            ("card_last4", "card_last4"),
            " tras usar un datáfono extraño",
        ],
        [
            "Detecté correos fraudulentos intentando obtener mis contraseñas bancarias",
        ],
        [
            "llamada sospechosa de alguien diciendo ser del banco pidiendo claves",
        ],
        [
            "Movimiento sospechoso: cambiaron mi correo registrado sin mi permiso",
        ],
        [
            "Alerta por vinculación de un nuevo dispositivo a mi cuenta el ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "notifique un mensaje falso de texto que recibi sobre bloqueo de cuenta",
        ],
        [
            "Alerta de seguridad de navegación no segura en mi banca virtual",
        ],
        [
            "Creo que mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            " fue vulnerada o copiada",
        ],
        [
            "Aviso de actividad inusual: solicitudes de token SMS que no pedí",
        ],
        [
            "me sale en la app un aviso de seguridad de ingreso bloqueado por sospecha",
        ],
        [
            "Registran intentos reiterados de cambio de PIN en mi tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "Aviso de seguridad por posible ataque de phishing a mi usuario",
        ],
        [
            "Veo actividad extraña en los registros de acceso a mi cuenta del día ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "sospecha de clonacion en cajero automatico con mi tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "Enlace fraudulento recibido por WhatsApp pidiendo datos de cuenta",
        ],
        [
            "Alerta del sistema sobre intentos bloqueados de acceso biométrico",
        ],
        [
            "reporto comportamiento anómalo en mi cuenta con avisos de seguridad",
        ],
        [
            "Tengo sospechas de fraude digital por mensajes extraños recibidos hoy",
        ],
    ],
    "request_card_block": [
        [
            "Por favor bloqueen mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            " inmediatamente",
        ],
        ["Quiero congelar mi tarjeta ", ("card_last4", "card_last4"), " por seguridad"],
        ["kiero bloqear mi tarjeta ", ("card_last4", "card_last4"), " ya"],
        [
            "URGENTE: bloquear la tarjeta número ",
            ("card_number", "card_number"),
            " de inmediato",
        ],
        [
            "Deseo suspender preventivamente mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
        ],
        ["bloqueen mi tarjeta ", ("card_last4", "card_last4"), " por favor"],
        [
            "Solicito el bloqueo definitivo de mi plástico terminado en ",
            ("card_last4", "card_last4"),
        ],
        ["Pongan candado a mi tarjeta terminada en ", ("card_last4", "card_last4")],
        [
            "porfa bloqueen ya la tarjeta ",
            ("card_last4", "card_last4"),
            " no quiero que la usen",
        ],
        ["Necesito inhabilitar mi tarjeta terminada en ", ("card_last4", "card_last4")],
        [
            "Bloquear tarjeta de crédito terminada en ",
            ("card_last4", "card_last4"),
            " ahora mismo",
        ],
        [
            "por favor congelar el plastico ",
            ("card_last4", "card_last4"),
            " preventivamente",
        ],
        [
            "Quiero apagar mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            " desde el sistema",
        ],
        ["bloqueo de tarjeta ", ("card_last4", "card_last4"), " urgente"],
        [
            "Solicito deshabilitar mi tarjeta número ",
            ("card_number", "card_number"),
            " por seguridad",
        ],
        [
            "Por seguridad necesito bloquear mi tarjeta débito terminada en ",
            ("card_last4", "card_last4"),
        ],
        ["inhabiliten mi tarjeta ", ("card_last4", "card_last4"), " de inmediato"],
        [
            "Quiero dar de baja y bloquear mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
        ],
        [
            "pueden bloquear mi tarjeta ",
            ("card_last4", "card_last4"),
            " para que no pasen cobros",
        ],
        [
            "Bloquear la tarjeta con terminación ",
            ("card_last4", "card_last4"),
            " por favor",
        ],
    ],
    "request_dispute": [
        [
            "Quiero iniciar una disputa por el cargo de ",
            ("currency", "currency"),
            ("amount", "amount"),
            " en ",
            ("merchant", "merchant"),
        ],
        [
            "Deseo reclamar y solicitar contracargo de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " cobrado en ",
            ("merchant", "merchant"),
            " el ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "kiero abrir una disputa para el cobro en ",
            ("merchant", "merchant"),
            " de ",
            ("currency", "currency"),
            ("amount", "amount"),
        ],
        [
            "Solicito formalmente el reembolso de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " por cobro indebido en ",
            ("merchant", "merchant"),
        ],
        [
            "Quiero disputar un cobro duplicado de ",
            ("currency", "currency"),
            ("amount", "amount"),
            " en ",
            ("merchant", "merchant"),
            " tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "necesito que me devuelvan ",
            ("currency", "currency"),
            ("amount", "amount"),
            " cobrados por ",
            ("merchant", "merchant"),
            " abran reclamo",
        ],
        [
            "Por favor inicien el proceso de reclamo de la transacción en ",
            ("merchant", "merchant"),
            " del ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "Reclamo formal por cobro no autorizado de ",
            ("currency", "currency"),
            ("amount", "amount"),
            " en ",
            ("merchant", "merchant"),
        ],
        [
            "quiero apelar la compra en ",
            ("merchant", "merchant"),
            " por ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
        ],
        [
            "Deseo abrir una queja formal y disputa por ",
            ("currency", "currency"),
            ("amount", "amount"),
            " en ",
            ("merchant", "merchant"),
        ],
        [
            "Abrir contracargo para la compra en ",
            ("merchant", "merchant"),
            " de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
        ],
        [
            "solicito disputa del cargo en ",
            ("merchant", "merchant"),
            " por ",
            ("currency", "currency"),
            ("amount", "amount"),
            " realizado ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "Quiero pedir el estorno de ",
            ("currency", "currency"),
            ("amount", "amount"),
            " de ",
            ("merchant", "merchant"),
        ],
        [
            "Presento reclamación por cargo erróneo de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " en ",
            ("merchant", "merchant"),
        ],
        [
            "disputar transaccion en ",
            ("merchant", "merchant"),
            " tarjeta terminada en ",
            ("card_last4", "card_last4"),
        ],
        [
            "Exijo la apertura de un expediente de disputa por ",
            ("currency", "currency"),
            ("amount", "amount"),
            " con ",
            ("merchant", "merchant"),
        ],
        [
            "Quiero desconocer legalmente y disputar el cobro de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " en ",
            ("merchant", "merchant"),
        ],
        [
            "deseo iniciar un contracargo comercial para ",
            ("merchant", "merchant"),
            " por ",
            ("currency", "currency"),
            ("amount", "amount"),
        ],
        [
            "Reclamar devolución de cobro en ",
            ("merchant", "merchant"),
            " por ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
        ],
        [
            "Por favor gestionar la disputa del cobro de ",
            ("currency", "currency"),
            ("amount", "amount"),
            " en ",
            ("merchant", "merchant"),
            " tarjeta ",
            ("card_last4", "card_last4"),
        ],
    ],
    "request_human_agent": [
        ["Quiero hablar con un asesor"],
        ["Pásame con una persona"],
        ["Necesito un agente humano"],
        ["No entiendo al bot quiero una persona real"],
        ["Transfiéreme con un ejecutivo"],
        ["Quiero atención con un operador humano"],
        ["Humano por favor"],
        ["Pónganme con alguien de soporte humano"],
        ["No quiero hablar con una máquina"],
        ["Conectar con asesor humano"],
        ["Por favor derívenme con un asesor"],
        ["Operador por favor"],
        ["Quiero hablar con alguien de atención al cliente"],
        ["Asesor humano urgente"],
        ["Pásame con un representante"],
        ["Por favor comuníquenme con un agente"],
        ["Necesito ayuda de una persona"],
        ["Quiero una persona de carne y hueso"],
        ["Atención personalizada por favor"],
        ["Transferir llamada o chat a humano"],
        ["No me sirve el robot quiero hablar con alguien"],
        ["Hablar con operador"],
        ["Quiero que me atienda un humano"],
        ["Pásame con un agente de soporte"],
        ["Comunícame con el área encargada humano"],
        ["Solicito atención humana"],
        ["Derivar a un operador"],
        ["No bot por favor agente"],
        ["Hablar con asesor"],
        ["Conectar con un humano"],
        ["Quiero hablar con un consultor"],
        ["Por favor un asesor real"],
        ["Pásame a servicio al cliente con una persona"],
        ["Agente humano por favor"],
        ["Necesito comunicarme con un agente de verdad"],
        ["Transferir con asesor comercial o soporte"],
        ["Quiero atención telefónica o asesor humano"],
        ["Ponme en contacto con un humano"],
        ["Asesor ya por favor"],
        ["Quiero comunicarme con alguien del equipo"],
    ],
    "provide_identity_data": [
        [
            "Mi nombre es ",
            ("full_name", "full_name"),
            ", tipo de documento ",
            ("document_type", "document_type"),
            " número ",
            ("document_number", "document_number"),
        ],
        [
            "Soy ",
            ("full_name", "full_name"),
            ", mi documento es ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            " y mi correo es ",
            ("email", "email"),
        ],
        [
            "mi nombre ",
            ("full_name", "full_name"),
            " fecha de nacimiento ",
            ("birth_date", "birth_date"),
            " telefono ",
            ("phone", "phone"),
        ],
        [
            "Mis datos son: nombre ",
            ("full_name", "full_name"),
            ", ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", teléfono ",
            ("phone", "phone"),
        ],
        [
            "hola me llamo ",
            ("full_name", "full_name"),
            " mi email es ",
            ("email", "email"),
            " y fecha de nacimiento ",
            ("birth_date", "birth_date"),
        ],
        [
            "Para verificarme: titular ",
            ("full_name", "full_name"),
            ", ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", nacido el ",
            ("birth_date", "birth_date"),
        ],
        [
            "Confirmo mi identidad: ",
            ("full_name", "full_name"),
            ", teléfono ",
            ("phone", "phone"),
            ", correo ",
            ("email", "email"),
        ],
        [
            "mi documento es ",
            ("document_type", "document_type"),
            " número ",
            ("document_number", "document_number"),
            " a nombre de ",
            ("full_name", "full_name"),
        ],
        [
            "Datos de verificación: nombre ",
            ("full_name", "full_name"),
            ", tarjeta ",
            ("card_number", "card_number"),
            ", correo ",
            ("email", "email"),
        ],
        [
            "Registro: ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", celular ",
            ("phone", "phone"),
            ", nacimiento ",
            ("birth_date", "birth_date"),
        ],
        [
            "Me identifico: ",
            ("full_name", "full_name"),
            ", documento ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
        ],
        [
            "Aqui mis datos de identificacion: ",
            ("full_name", "full_name"),
            " y documento ",
            ("document_number", "document_number"),
        ],
        [
            "nombre ",
            ("full_name", "full_name"),
            ", documento tipo ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", email ",
            ("email", "email"),
        ],
        [
            "Soy titular ",
            ("full_name", "full_name"),
            ", fecha ",
            ("birth_date", "birth_date"),
            ", celular ",
            ("phone", "phone"),
        ],
        [
            "documento ",
            ("document_type", "document_type"),
            " con número ",
            ("document_number", "document_number"),
            " correspondiente a ",
            ("full_name", "full_name"),
        ],
        [
            "datos: ",
            ("full_name", "full_name"),
            ", ",
            ("email", "email"),
            ", ",
            ("phone", "phone"),
            ", ",
            ("document_number", "document_number"),
        ],
        [
            "Nombre del titular: ",
            ("full_name", "full_name"),
            ", tipo ",
            ("document_type", "document_type"),
            ", número ",
            ("document_number", "document_number"),
        ],
        [
            "hola, soy ",
            ("full_name", "full_name"),
            ", mi tarjeta es ",
            ("card_number", "card_number"),
            " y mi email ",
            ("email", "email"),
        ],
        [
            "Identidad: ",
            ("full_name", "full_name"),
            ", fecha de nacimiento ",
            ("birth_date", "birth_date"),
            ", doc ",
            ("document_number", "document_number"),
        ],
        [
            "Proporciono mis datos personales: ",
            ("full_name", "full_name"),
            ", ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", teléfono ",
            ("phone", "phone"),
        ],
    ],
    "provide_otp_code": [
        ["El código que me llegó es ", ("otp_code", "otp_code")],
        ["Mi clave de un solo uso es ", ("otp_code", "otp_code")],
        ["el codigo otp es ", ("otp_code", "otp_code")],
        ["Acabo de recibir el código: ", ("otp_code", "otp_code")],
        ["Ingrese el código ", ("otp_code", "otp_code"), " que llegó a mi celular"],
        ["codigo de verificacion: ", ("otp_code", "otp_code")],
        ["El token SMS es ", ("otp_code", "otp_code")],
        ["Aqui tienes el codigo que llego: ", ("otp_code", "otp_code")],
        ["Listo, mi código de seguridad es ", ("otp_code", "otp_code")],
        ["el codigo que recibi es ", ("otp_code", "otp_code"), " porfa confirmar"],
        ["Mi código de autorización recibido es ", ("otp_code", "otp_code")],
        ["Token de verificación: ", ("otp_code", "otp_code")],
        ["ya me llego la clave dinamica ", ("otp_code", "otp_code")],
        ["El código OTP recibido por mensaje es ", ("otp_code", "otp_code")],
        ["Confirmo con el código ", ("otp_code", "otp_code")],
        ["mi otp es ", ("otp_code", "otp_code")],
        ["Clave de un solo paso: ", ("otp_code", "otp_code")],
        ["El código temporal que me enviaron es ", ("otp_code", "otp_code")],
        ["código SMS ", ("otp_code", "otp_code"), " recibido"],
        ["Le proporciono el número de verificación: ", ("otp_code", "otp_code")],
    ],
    "confirm": [
        ["Sí"],
        ["Si confirmo"],
        ["De acuerdo"],
        ["Correcto"],
        ["Sí por favor"],
        ["Si proceda"],
        ["Confirmado"],
        ["Estoy de acuerdo"],
        ["Adelante"],
        ["Si es correcto"],
        ["Dale confirmo"],
        ["Si por favor procedan"],
        ["Correcto esa es mi solicitud"],
        ["Si autorizo la operacion"],
        ["Por supuesto confirmo"],
        ["Si quiero continuar"],
        ["Exactamente eso es"],
        ["Si por favor háganlo"],
        ["Totalmente de acuerdo"],
        ["Siafirmo"],
        ["Claro que si"],
        ["Si acepto"],
        ["Correcto haganlo ya"],
        ["Si proceder con el proceso"],
        ["Confirmar accion"],
        ["Si adelante con eso"],
        ["Si confirmo la operacion indicada"],
        ["Por favor proceda"],
        ["Si estoy seguro"],
        ["De una hagamoslo"],
        ["Si claro confirmo"],
        ["Si correcto procedan"],
        ["Afirmativo"],
        ["Confirmo la peticion"],
        ["Si autorizo"],
        ["Si deseo proceder"],
        ["Correcto continúe"],
        ["Si por mi esta bien"],
        ["Si confirmo todo"],
        ["De acuerdo procedan"],
    ],
    "deny": [
        ["No"],
        ["No no quiero"],
        ["Cancelar"],
        ["No cancelen todo"],
        ["No estoy de acuerdo"],
        ["Negativo"],
        ["Para nada"],
        ["No no proceda"],
        ["No autorizo esto"],
        ["Rechazar"],
        ["No quiero continuar"],
        ["Cancela esa accion"],
        ["No de ninguna manera"],
        ["No es correcto"],
        ["No por favor no lo hagan"],
        ["No cancelalo"],
        ["Detener proceso"],
        ["No estoy seguro mejor no"],
        ["No no deseo hacerlo"],
        ["Rechazo la solicitud"],
        ["No abortar"],
        ["No para nada gracias"],
        ["No quiero cancelar la solicitud"],
        ["No nada que ver"],
        ["No eso no fue asi"],
        ["No parar aqui"],
        ["No cancelar operacion"],
        ["No autorizo el cargo"],
        ["No deseo proceder"],
        ["No me parece"],
        ["No descarten la solicitud"],
        ["No prefiero no continuar"],
        ["No rechazo esa opcion"],
        ["Cancelar pedido"],
        ["No no acepto"],
        ["No no es asi"],
        ["No por favor espere"],
        ["No dejenlo asi"],
        ["No detener todo"],
        ["No me arrepenti"],
    ],
    "check_balance": [
        [
            "¿Cuál es el saldo disponible en mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            "?",
        ],
        ["Quiero consultar el saldo actual de mi cuenta"],
        ["kiero saber cuanto saldo tengo en mi tarjeta ", ("card_last4", "card_last4")],
        [
            "Buenas tardes, ¿pueden informarme el saldo de mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            "?",
        ],
        ["saldo de mi tarjeta ", ("card_last4", "card_last4"), " por favor"],
        [
            "¿Cuánto dinero tengo en mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            "?",
        ],
        [
            "Deseo conocer el cupo disponible en mi tarjeta ",
            ("card_last4", "card_last4"),
        ],
        ["cuanto saldo me queda en la tarjeta ", ("card_last4", "card_last4")],
        [
            "Por favor indíqueme el saldo de mi cuenta asociada a la tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "Consulta de saldo disponible en la tarjeta terminada en ",
            ("card_last4", "card_last4"),
        ],
        [
            "¿Cuánto crédito disponible tengo en la tarjeta ",
            ("card_last4", "card_last4"),
            "?",
        ],
        ["quiero saber mi saldo actual en la tarjeta ", ("card_last4", "card_last4")],
        ["Consultar balance de cuenta y tarjeta ", ("card_last4", "card_last4")],
        [
            "¿Qué saldo tengo en mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            "?",
        ],
        ["saldo disponible por favor tarjeta ", ("card_last4", "card_last4")],
        ["Deseo ver cuánto dinero tengo en la tarjeta ", ("card_last4", "card_last4")],
        ["Información de saldo de mi plástico ", ("card_last4", "card_last4")],
        ["pueden decirme el saldo de mi tarjeta ", ("card_last4", "card_last4")],
        [
            "Cuánto tengo disponible en la tarjeta terminada en ",
            ("card_last4", "card_last4"),
        ],
        ["Ver saldo actual de la tarjeta débito ", ("card_last4", "card_last4")],
    ],
    "check_recent_transactions": [
        [
            "Quiero ver los últimos movimientos de mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
        ],
        ["¿Me pueden mostrar mis transacciones recientes?"],
        ["kiero ver mis ultimos gastos en la tarjeta ", ("card_last4", "card_last4")],
        [
            "Buenas tardes, deseo consultar el historial de compras de mi tarjeta ",
            ("card_last4", "card_last4"),
        ],
        ["ultimos movimientos de la tarjeta ", ("card_last4", "card_last4"), " porfa"],
        [
            "Listar por favor las transacciones realizadas en mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
        ],
        [
            "¿Cuáles fueron las compras que hice recientemente con mi tarjeta ",
            ("card_last4", "card_last4"),
            "?",
        ],
        ["mostrar movimientos recientes de mi tarjeta ", ("card_last4", "card_last4")],
        [
            "Deseo revisar los últimos pagos registrados en mi tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "Historial de transacciones de mi plástico terminado en ",
            ("card_last4", "card_last4"),
        ],
        [
            "¿Cuáles son los consumos recientes en mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            "?",
        ],
        ["listar ultimos movimientos tarjeta ", ("card_last4", "card_last4")],
        [
            "Quiero consultar las compras de esta semana en mi tarjeta ",
            ("card_last4", "card_last4"),
        ],
        ["ver extracto reciente de tarjeta ", ("card_last4", "card_last4")],
        [
            "¿Qué transacciones se han cobrado últimamente en mi tarjeta ",
            ("card_last4", "card_last4"),
            "?",
        ],
        [
            "Movimientos recientes de mi tarjeta débito terminada en ",
            ("card_last4", "card_last4"),
        ],
        ["muestrenme los ultimos cobros de la tarjeta ", ("card_last4", "card_last4")],
        [
            "Deseo ver las operaciones recientes en mi tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "Revisar historial reciente de movimientos en tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "Consultar últimas compras con mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
        ],
    ],
    "greeting": [
        ["Hola"],
        ["Hola buenos días"],
        ["Buenas tardes"],
        ["Hola buenas noches"],
        ["Hola qué tal"],
        ["Buen día"],
        ["Hola buenas"],
        ["Buenos dias equipo"],
        ["Hola quisiera hacer una consulta"],
        ["Hola necesito ayuda"],
        ["Buenas"],
        ["Que tal como estas"],
        ["Hola hola"],
        ["Buen dia por favor"],
        ["Saludos cordiales"],
        ["Hola estimado agente"],
        ["Buenas tardes un gusto saludar"],
        ["Hola muy buen dia"],
        ["Hola que tal como te va"],
        ["Buenos dias senores"],
        ["Hola tengo una pregunta"],
        ["Buenas noches a todos"],
        ["Hola cordial saludo"],
        ["Buen dia equipo de atencion"],
        ["Hola quiero consultar algo"],
        ["Buenas tardes disculpe la molestia"],
        ["Hola buen dia me podrian colaborar"],
        ["Que tal buen dia"],
        ["Hola por aqui necesito asistencia"],
        ["Buenas como estan"],
        ["Hola quisiera comunicarme con ustedes"],
        ["Saludos buen dia"],
        ["Hola atencion al cliente"],
        ["Buen dia cordial saludo"],
        ["Hola necesito comunicarme"],
        ["Buenas tardes queria consultar una cosa"],
        ["Hola inicio de chat"],
        ["Que tal buenas tardes"],
        ["Hola contacto con soporte"],
        ["Buenos dias me ayudan por favor"],
    ],
    "out_of_scope": [
        ["¿Cuál es la receta para hacer pizza?"],
        ["¿Cómo está el clima hoy en Madrid?"],
        ["¿Quién ganó el mundial de fútbol?"],
        ["Cuéntame un chiste"],
        ["¿Qué es la teoría de la relatividad?"],
        ["Recomiéndame una película de ciencia ficción"],
        ["¿Cuánto cuesta un vuelo a París?"],
        ["¿Cómo puedo arreglar una llanta pinchada?"],
        ["¿Cuál es la capital de Australia?"],
        ["Dime un poema sobre el mar"],
        ["¿Qué hora es en Tokio?"],
        ["¿Cómo se prepara el café irlandés?"],
        ["¿Cuáles son los planetas del sistema solar?"],
        ["Ayúdame con mi tarea de matemáticas"],
        ["¿Cómo aprender a programar en Rust?"],
        ["¿Quién pintó la Mona Lisa?"],
        ["¿Por qué el cielo es azul?"],
        ["¿Qué canciones están de moda?"],
        ["Traduce esta frase al francés"],
        ["¿Cuál es el mejor restaurante italiano?"],
        ["¿Cómo curar un resfriado común?"],
        ["¿Qué distancia hay entre el sol y la tierra?"],
        ["¿Cómo cambiar el aceite de mi carro?"],
        ["¿Quién descubrió América?"],
        ["¿Cuál es el animal más rápido del mundo?"],
        ["¿Cómo hacer ejercicio en casa?"],
        ["¿Qué ingredientes lleva la paella?"],
        ["¿Cómo funciona un motor eléctrico?"],
        ["¿Cuál es el libro más vendido de la historia?"],
        ["¿Qué ropa debo usar si llueve?"],
        ["¿Cómo cultivar tomates en mi jardín?"],
        ["¿Quién inventó el teléfono?"],
        ["¿Cuál es la montaña más alta del mundo?"],
        ["¿Cómo tocar la guitarra?"],
        ["¿Qué películas hay en el cine hoy?"],
        ["¿Cuál es la velocidad de la luz?"],
        ["¿Cómo escribir una novela?"],
        ["¿Por qué las hojas son verdes?"],
        ["¿Cuál es la moneda de Japón?"],
        ["¿Cómo hacer pan casero?"],
    ],
}

VAL_TEMPLATES: dict[str, list[Template]] = {
    "report_unrecognized_charge": [
        [
            "Desconozco totalmente un movimiento por ",
            ("currency", "currency"),
            ("amount", "amount"),
            " en ",
            ("merchant", "merchant"),
            " en la tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "Me cobraron ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " en ",
            ("merchant", "merchant"),
            " pero yo no compré nada",
        ],
        [
            "En el extracto aparece un cobro no identificado de ",
            ("currency", "currency"),
            ("amount", "amount"),
            " en ",
            ("merchant", "merchant"),
            " del ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "veo una transaccion que no hice de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " en ",
            ("merchant", "merchant"),
            " tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "Estimado soporte, desconozco un consumo de ",
            ("currency", "currency"),
            ("amount", "amount"),
            " registrado en ",
            ("merchant", "merchant"),
        ],
        [
            "No reconozco el débito por ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " en ",
            ("merchant", "merchant"),
            " con mi tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "Apareció un gasto desconocido en ",
            ("merchant", "merchant"),
            " por valor de ",
            ("currency", "currency"),
            ("amount", "amount"),
        ],
        [
            "Cobro extraño en ",
            ("merchant", "merchant"),
            " de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " en fecha ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "no autorice el cobro de ",
            ("currency", "currency"),
            ("amount", "amount"),
            " proveniente de ",
            ("merchant", "merchant"),
        ],
        [
            "Tengo un cargo imprevisto de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " en ",
            ("merchant", "merchant"),
            " en la tarjeta ",
            ("card_last4", "card_last4"),
        ],
    ],
    "report_lost_card": [
        [
            "Extravié mi tarjeta débito con terminación ",
            ("card_last4", "card_last4"),
            " hoy en la mañana",
        ],
        [
            "No puedo localizar mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            ", se me cayó en la calle",
        ],
        ["perdi mi tarjeta ", ("card_last4", "card_last4"), " y necesito reportarlo"],
        [
            "Olvidé dónde dejé mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            " y no aparece",
        ],
        [
            "Reporte de extravío de tarjeta con últimos dígitos ",
            ("card_last4", "card_last4"),
        ],
        [
            "He perdido mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            " en el aeropuerto",
        ],
        [
            "Dejé mi plástico terminado en ",
            ("card_last4", "card_last4"),
            " en un local comercial",
        ],
        [
            "se me perdio la tarjeta de credito ",
            ("card_number", "card_number"),
            " hace un momento",
        ],
        [
            "No sé dónde está mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            ", la extravié",
        ],
        [
            "Extravío involuntario de tarjeta ",
            ("card_last4", "card_last4"),
            " en el transporte público",
        ],
    ],
    "report_stolen_card": [
        [
            "Me asaltaron hoy y me robaron mi tarjeta de débito ",
            ("card_last4", "card_last4"),
        ],
        [
            "Alguien me sacó la tarjeta terminada en ",
            ("card_last4", "card_last4"),
            " de la mochila",
        ],
        [
            "me robaron el plastico terminado en ",
            ("card_last4", "card_last4"),
            " ayudenme",
        ],
        [
            "Sufro el robo de mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            " en el transporte público",
        ],
        [
            "Reporte urgente: delincuentes me robaron mi tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "Fui víctima de atraco a mano armada y me quitaron la tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "Me robaron el bolso con mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            " en un café",
        ],
        [
            "hurto de la tarjeta numero ",
            ("card_number", "card_number"),
            " en horas de la tarde",
        ],
        ["Acaban de robarme y sustrajeron mi tarjeta ", ("card_last4", "card_last4")],
        [
            "Denuncia de sustracción violenta de tarjeta terminada en ",
            ("card_last4", "card_last4"),
        ],
    ],
    "report_suspicious_activity": [
        [
            "Noto actividad sospechosa en mi tarjeta ",
            ("card_last4", "card_last4"),
            " con alertas de seguridad del sistema",
        ],
        [
            "Aviso de intento de acceso no reconocido a mi banca móvil",
        ],
        [
            "alerta de inicio de sesion sospechoso detectado el ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "Creo que alguien intenta acceder a mi cuenta de forma no autorizada",
        ],
        [
            "Aviso de señales anómalas de seguridad en mi perfil bancario",
        ],
        [
            "Actividad inusual detectada: recibí código de autenticación no pedido",
        ],
        [
            "sospecho vulneracion de mi tarjeta ",
            ("card_last4", "card_last4"),
            " por intento de clonado",
        ],
        [
            "Mensaje falso sospechoso pidiendo mis datos bancarios",
        ],
        [
            "Reporte preventivo de sospecha de clonación en cajero automático",
        ],
        [
            "Alerta del banco sobre inicio de sesión desde ubicación desconocida",
        ],
    ],
    "request_card_block": [
        [
            "Por favor desactiven de inmediato mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
        ],
        [
            "Requiero bloquear mi tarjeta débito terminada en ",
            ("card_last4", "card_last4"),
            " de manera urgente",
        ],
        ["bloquear tarjeta ", ("card_last4", "card_last4"), " cuanto antes"],
        [
            "Solicito la congelación inmediata de mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
        ],
        [
            "Procedan a bloquear mi plástico con terminación ",
            ("card_last4", "card_last4"),
        ],
        ["Deseo inhabilitar de inmediato mi tarjeta ", ("card_number", "card_number")],
        ["por favor bloquenla ya, tarjeta terminada en ", ("card_last4", "card_last4")],
        ["Poner bloqueo de seguridad en la tarjeta ", ("card_last4", "card_last4")],
        [
            "Quiero bloquear por completo el uso de mi tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "Desactivación urgente de mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
        ],
    ],
    "request_dispute": [
        [
            "Vengo a solicitar un contracargo formal por ",
            ("currency", "currency"),
            ("amount", "amount"),
            " realizado en ",
            ("merchant", "merchant"),
        ],
        [
            "Deseo impugnar la transacción de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " en ",
            ("merchant", "merchant"),
            " fecha ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "abrir disputa de compra en ",
            ("merchant", "merchant"),
            " por ",
            ("currency", "currency"),
            ("amount", "amount"),
        ],
        [
            "Exijo la devolución y disputa del monto de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " cobrado por ",
            ("merchant", "merchant"),
        ],
        [
            "Por favor procedan con el proceso de disputa para el movimiento en ",
            ("merchant", "merchant"),
            " de mi tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "Quiero iniciar formalmente la disputa comercial en ",
            ("merchant", "merchant"),
            " por ",
            ("currency", "currency"),
            ("amount", "amount"),
        ],
        [
            "Reclamación para anular cobro y solicitar contracargo de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " en ",
            ("merchant", "merchant"),
        ],
        [
            "Disputo el pago en ",
            ("merchant", "merchant"),
            " por valor de ",
            ("currency", "currency"),
            ("amount", "amount"),
            " realizado ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "solicitud de contracargo bancario para la transaccion en ",
            ("merchant", "merchant"),
            " de ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
        ],
        [
            "Deseo abrir una reclamación formal por ",
            ("currency", "currency"),
            ("amount", "amount"),
            " con ",
            ("merchant", "merchant"),
            " tarjeta ",
            ("card_last4", "card_last4"),
        ],
    ],
    "request_human_agent": [
        ["Por favor transferirme con un operador de soporte"],
        ["Quiero comunicarme con un ejecutivo humano"],
        ["Solicito hablar directamente con un agente"],
        ["Póngame con una persona real por favor"],
        ["Derivar esta conversación a un asesor humano"],
        ["Necesito soporte de un representante humano"],
        ["No deseo hablar con el bot transfiérame"],
        ["Quiero ser atendido por un agente humano"],
        ["Comuníqueme por favor con un asesor disponible"],
        ["Por favor pasar con personal de atención"],
    ],
    "provide_identity_data": [
        [
            "Verificación de identidad: me llamo ",
            ("full_name", "full_name"),
            ", ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", email ",
            ("email", "email"),
        ],
        [
            "Mis datos personales son ",
            ("full_name", "full_name"),
            ", nacido el ",
            ("birth_date", "birth_date"),
            " y móvil ",
            ("phone", "phone"),
        ],
        [
            "aqui estan mis datos ",
            ("full_name", "full_name"),
            " documento ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
        ],
        [
            "Nombre completo ",
            ("full_name", "full_name"),
            ", teléfono de contacto ",
            ("phone", "phone"),
            ", documento ",
            ("document_number", "document_number"),
        ],
        [
            "Proporciono mi ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", correo ",
            ("email", "email"),
            " fecha ",
            ("birth_date", "birth_date"),
        ],
        [
            "Titular ",
            ("full_name", "full_name"),
            ", tarjeta ",
            ("card_number", "card_number"),
            ", teléfono ",
            ("phone", "phone"),
        ],
        [
            "me identifico como ",
            ("full_name", "full_name"),
            " con ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            " y mail ",
            ("email", "email"),
        ],
        [
            "Mis datos de cliente: ",
            ("full_name", "full_name"),
            ", fecha ",
            ("birth_date", "birth_date"),
            ", doc ",
            ("document_number", "document_number"),
        ],
        [
            "Identificación formal: ",
            ("full_name", "full_name"),
            ", ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", celular ",
            ("phone", "phone"),
        ],
        [
            "Registro de identidad: ",
            ("full_name", "full_name"),
            ", fecha de nacimiento ",
            ("birth_date", "birth_date"),
            ", email ",
            ("email", "email"),
        ],
    ],
    "provide_otp_code": [
        [
            "El número de confirmación recibido por mensaje es ",
            ("otp_code", "otp_code"),
        ],
        ["Mi código OTP para autorizar la operación es ", ("otp_code", "otp_code")],
        ["ya me llego el codigo otp ", ("otp_code", "otp_code")],
        ["Proporciono el código de verificación temporal: ", ("otp_code", "otp_code")],
        ["Código recibido en mi teléfono: ", ("otp_code", "otp_code")],
        ["El código que me mandaron al celular es ", ("otp_code", "otp_code")],
        ["Clave dinámica recibida por SMS: ", ("otp_code", "otp_code")],
        ["este es el otp ", ("otp_code", "otp_code")],
        ["Introduzco el código de seguridad ", ("otp_code", "otp_code"), " solicitado"],
        ["Token temporal de confirmación: ", ("otp_code", "otp_code")],
    ],
    "confirm": [
        ["Efectivamente confirmo"],
        ["Si de acuerdo haganlo"],
        ["Proceda por favor con la solicitud"],
        ["Si es lo que deseo"],
        ["Confirmo los datos"],
        ["Si prosiga"],
        ["Si confirmo el requerimiento"],
        ["Correcto siga adelante"],
        ["Acepto y confirmo"],
        ["Si totalmente confirmado"],
    ],
    "deny": [
        ["No rechazo la operacion"],
        ["No detener inmediatamente"],
        ["Cancelar no deseo proceder"],
        ["No no estoy de acuerdo con eso"],
        ["No anulen el proceso"],
        ["No cancelen la solicitud por favor"],
        ["No definitivamente no"],
        ["No descarto la accion"],
        ["No denegar"],
        ["No no autorizo que continuen"],
    ],
    "check_balance": [
        [
            "¿Me podría indicar el saldo actual de mi plástico terminado en ",
            ("card_last4", "card_last4"),
            "?",
        ],
        [
            "Quisiera verificar el monto disponible en mi tarjeta ",
            ("card_last4", "card_last4"),
        ],
        ["consultar saldo tarjeta ", ("card_last4", "card_last4"), " por favor"],
        [
            "¿Cuál es el balance disponible en mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            "?",
        ],
        [
            "Deseo consultar cuánto crédito tengo disponible en mi tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "Por favor informarme el saldo restante de mi tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "cuanto dinero tengo en la tarjeta terminada en ",
            ("card_last4", "card_last4"),
        ],
        [
            "Solicitud de saldo de cuenta asociada a tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "¿Cuánto dinero disponible tengo actualmente en mi plástico ",
            ("card_last4", "card_last4"),
            "?",
        ],
        ["Consultar fondos disponibles en tarjeta ", ("card_last4", "card_last4")],
    ],
    "check_recent_transactions": [
        [
            "¿Podrían detallarme las compras más recientes de mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
            "?",
        ],
        [
            "Quisiera consultar los movimientos de esta semana en mi tarjeta ",
            ("card_last4", "card_last4"),
        ],
        ["ver lista de ultimas compras en mi tarjeta ", ("card_last4", "card_last4")],
        [
            "Por favor muéstrenme los débitos recientes en mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
        ],
        [
            "Deseo consultar el historial de movimientos asociados a mi tarjeta ",
            ("card_last4", "card_last4"),
        ],
        [
            "¿Qué gastos se han cargado recientemente a mi tarjeta ",
            ("card_last4", "card_last4"),
            "?",
        ],
        [
            "Revisión de transacciones de los últimos días en mi plástico ",
            ("card_last4", "card_last4"),
        ],
        [
            "muestrenme los consumos de la tarjeta ",
            ("card_last4", "card_last4"),
            " de este mes",
        ],
        [
            "Historial de pagos y compras de mi tarjeta terminada en ",
            ("card_last4", "card_last4"),
        ],
        [
            "Listado de movimientos recientes en mi tarjeta ",
            ("card_last4", "card_last4"),
        ],
    ],
    "greeting": [
        ["Hola buen día a todos"],
        ["Muy buenas tardes"],
        ["Hola un saludo para el soporte"],
        ["Buenas estimados"],
        ["Hola tengo dudas sobre mi servicio"],
        ["Buenos dias deseo hacer una consulta"],
        ["Hola buenas me gustaria consultar algo"],
        ["Buenas noches estimado equipo"],
        ["Hola que tal buenas"],
        ["Saludos cordiales al equipo de atencion"],
    ],
    "out_of_scope": [
        ["¿Cuál es el río más largo del mundo?"],
        ["¿Cómo preparar sushi en casa?"],
        ["¿Quién escribió Cien años de soledad?"],
        ["¿A qué distancia está Marte de la Tierra?"],
        ["¿Cómo cuidar una planta suculenta?"],
        ["¿Cuál es la capital de Canadá?"],
        ["¿Cómo aprender a pintar con acuarela?"],
        ["¿Quién descubrió la penicilina?"],
        ["¿Por qué parpadean las estrellas?"],
        ["¿Cómo hacer yoga para principiantes?"],
    ],
}
