"""English templates for intent and slot generation.

Contains:
- 15 intents
- 40 train templates/phrases per intent
- 10 validation templates/phrases per intent (strictly disjoint from train)
- Varied linguistic registers, casing, colloquialisms, and common typos.
"""

Template = list[str | tuple[str, str]]

TRAIN_TEMPLATES: dict[str, list[Template]] = {
    "report_unrecognized_charge": [
        [
            "I do not recognize a charge of ",
            ("currency", "currency"),
            ("amount", "amount"),
            " at ",
            ("merchant", "merchant"),
            " on my card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "There is an unknown purchase of ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " from ",
            ("merchant", "merchant"),
            " on ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "hi unrecogized charge at ",
            ("merchant", "merchant"),
            " for ",
            ("currency", "currency"),
            ("amount", "amount"),
        ],
        [
            "URGENT: unrecognized charge of ",
            ("currency", "currency"),
            ("amount", "amount"),
            " at ",
            ("merchant", "merchant"),
            " on card ",
            ("card_last4", "card_last4"),
        ],
        [
            "I noticed an unauthorized debit from ",
            ("merchant", "merchant"),
            " for ",
            ("currency", "currency"),
            ("amount", "amount"),
        ],
        [
            "my card was charged ",
            ("currency", "currency"),
            ("amount", "amount"),
            " by ",
            ("merchant", "merchant"),
            " and i never bought that",
        ],
        [
            "I do not recognize the transaction of ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " at ",
            ("merchant", "merchant"),
            " on card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "Reporting an unfamiliar transaction from ",
            ("merchant", "merchant"),
            " of ",
            ("currency", "currency"),
            ("amount", "amount"),
            " dated ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "someone used my card ",
            ("card_last4", "card_last4"),
            " at ",
            ("merchant", "merchant"),
            " for ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
        ],
        [
            "There is a strange withdrawal of ",
            ("currency", "currency"),
            ("amount", "amount"),
            " by ",
            ("merchant", "merchant"),
            " that I did not make",
        ],
        [
            "i did not authorize this purchase at ",
            ("merchant", "merchant"),
            " of ",
            ("currency", "currency"),
            ("amount", "amount"),
        ],
        [
            "Notice of suspicious charge: ",
            ("merchant", "merchant"),
            " billed ",
            ("currency", "currency"),
            ("amount", "amount"),
            " on card ",
            ("card_last4", "card_last4"),
        ],
        [
            "saw an unknown charge on my bank statement from ",
            ("merchant", "merchant"),
            " for ",
            ("currency", "currency"),
            ("amount", "amount"),
        ],
        [
            "A charge of ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " from ",
            ("merchant", "merchant"),
            " appeared on my card ",
            ("card_last4", "card_last4"),
        ],
        [
            "unrecognized debit from ",
            ("merchant", "merchant"),
            " on ",
            ("transaction_date", "transaction_date"),
            " of ",
            ("currency", "currency"),
            ("amount", "amount"),
        ],
        [
            "Unidentified charge of ",
            ("currency", "currency"),
            ("amount", "amount"),
            " from ",
            ("merchant", "merchant"),
            " on card ",
            ("card_last4", "card_last4"),
        ],
        [
            "I want to report a fraudulent transaction of ",
            ("currency", "currency"),
            ("amount", "amount"),
            " at ",
            ("merchant", "merchant"),
        ],
        [
            "Got a notification for a charge of ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " at ",
            ("merchant", "merchant"),
            " which I did not authorize",
        ],
        [
            "weird transaction on my statement from ",
            ("merchant", "merchant"),
            " for ",
            ("currency", "currency"),
            ("amount", "amount"),
        ],
        [
            "Unexpected charge on card ending in ",
            ("card_last4", "card_last4"),
            " for ",
            ("currency", "currency"),
            ("amount", "amount"),
            " at ",
            ("merchant", "merchant"),
        ],
    ],
    "report_lost_card": [
        [
            "I lost my card ending in ",
            ("card_last4", "card_last4"),
            " at the shopping mall",
        ],
        [
            "I misplaced my card ",
            ("card_last4", "card_last4"),
            " and cannot find it anywhere",
        ],
        [
            "think i lost my debit card ",
            ("card_last4", "card_last4"),
            " in a cab yesterday",
        ],
        ["URGENTE: lost my credit card number ", ("card_number", "card_number")],
        [
            "I cannot locate my payment card with last digits ",
            ("card_last4", "card_last4"),
        ],
        ["hi i lost my card ", ("card_last4", "card_last4"), " how do i report it"],
        [
            "I accidentally left my card ending in ",
            ("card_last4", "card_last4"),
            " at a coffee shop",
        ],
        [
            "I lost my card ending in ",
            ("card_last4", "card_last4"),
            " while traveling abroad",
        ],
        [
            "dropped my plastic card ending in ",
            ("card_last4", "card_last4"),
            " somewhere outside",
        ],
        [
            "Good afternoon, reporting the loss of my card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "Lost card report: cannot find my card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "misplaced my card ",
            ("card_last4", "card_last4"),
            " this morning please help",
        ],
        [
            "I lost my wallet containing my debit card ending in ",
            ("card_last4", "card_last4"),
        ],
        ["Left my card ", ("card_last4", "card_last4"), " in an ATM and it is gone"],
        ["notice of lost card ending in ", ("card_last4", "card_last4")],
        [
            "I have searched everywhere for my card ",
            ("card_last4", "card_last4"),
            " but cannot find it",
        ],
        ["Lost my credit card ", ("card_number", "card_number"), " a few hours ago"],
        [
            "think i dropped my card ",
            ("card_last4", "card_last4"),
            " at the grocery store",
        ],
        ["I have lost my debit card ending in ", ("card_last4", "card_last4")],
        [
            "Reporting that I lost my card with full number ",
            ("card_number", "card_number"),
        ],
    ],
    "report_stolen_card": [
        ["My wallet was stolen with my card ending in ", ("card_last4", "card_last4")],
        ["Someone mugged me and took my card ending in ", ("card_last4", "card_last4")],
        ["my card ", ("card_last4", "card_last4"), " was stolen on the subway"],
        ["URGENT: my card number ", ("card_number", "card_number"), " was just stolen"],
        [
            "I was robbed and my card ending in ",
            ("card_last4", "card_last4"),
            " was taken",
        ],
        [
            "thieves took my bag containing card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "My debit card ending in ",
            ("card_last4", "card_last4"),
            " was stolen from my gym locker",
        ],
        [
            "Someone broke into my car and stole my card ending in ",
            ("card_last4", "card_last4"),
        ],
        ["hi my purse was stolen with card ", ("card_last4", "card_last4")],
        [
            "Reporting theft of my card ending in ",
            ("card_last4", "card_last4"),
            " at gunpoint",
        ],
        [
            "Criminals snatched my card ending in ",
            ("card_last4", "card_last4"),
            " just now",
        ],
        [
            "card theft: card ending in ",
            ("card_last4", "card_last4"),
            " stolen on public transit",
        ],
        [
            "Someone pickpocketed me and took my card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "my card was stolen, please note card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "Formal report: stolen card ",
            ("card_number", "card_number"),
            " earlier today",
        ],
        [
            "I was held up and robbed of my debit card ending in ",
            ("card_last4", "card_last4"),
        ],
        ["stolen card ", ("card_last4", "card_last4"), " reported in downtown"],
        ["Someone unlawfully took my card ending in ", ("card_last4", "card_last4")],
        [
            "my belongings were stolen including card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "Notifying customer service that my card ending in ",
            ("card_last4", "card_last4"),
            " was stolen",
        ],
    ],
    "report_suspicious_activity": [
        [
            "Suspicious text message about unrecognized login to mobile banking",
        ],
        [
            "Suspicious account activity: failed login attempts from another device",
        ],
        [
            "got a fraud alert sms asking for card details for card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "Security alert: strange login attempts on my account from another country",
        ],
        [
            "I detected anomalous activity on my banking profile on ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "got an otp code i never requested sent to my phone",
        ],
        [
            "I suspect someone tried to clone my card ",
            ("card_last4", "card_last4"),
            " at an atm",
        ],
        [
            "Multiple suspicious verification code notices that I did not generate",
        ],
        [
            "security alert: unauthorized password reset attempt on my account",
        ],
        [
            "Reporting potential fraud and unauthorized login attempts on my account",
        ],
        [
            "Suspicious activity notice: phishing email claiming to be from the bank",
        ],
        [
            "weird notification about blocked login attempts on my mobile app",
        ],
        [
            "Bank notified me of unrecognized access from an unfamiliar IP address",
        ],
        [
            "Suspicious access attempt detected on ",
            ("transaction_date", "transaction_date"),
            " on my account",
        ],
        [
            "security warning for potential skimming or cloning on card ",
            ("card_last4", "card_last4"),
        ],
        [
            "System security notice regarding preventative block on card ",
            ("card_last4", "card_last4"),
        ],
        [
            "I think someone is trying to breach my account using fraudulent messages",
        ],
        [
            "Received security warnings about repeated failed passcode entries",
        ],
        [
            "fraud suspicion on card ",
            ("card_last4", "card_last4"),
            " after strange terminal alert",
        ],
        [
            "Suspicious security alerts showing unexpected activity on my username",
        ],
        [
            "Urgent notice: received security alert about sign-in from unknown phone",
        ],
        [
            "Someone is trying to access my app, multiple bad password warnings",
        ],
        [
            "suspicious fraud attempt on card ending in ",
            ("card_last4", "card_last4"),
            " after using a sketchy terminal",
        ],
        [
            "phishing emails trying to trick me into giving up my banking password",
        ],
        [
            "suspicious call from someone pretending to be bank staff asking for PIN",
        ],
        [
            "Suspicious profile activity: someone attempted to change my email",
        ],
        [
            "Alert about an unauthorized device link request on my mobile banking on ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "reporting a fake sms text message stating my account was locked",
        ],
        [
            "My app shows a security block alert due to suspicious activity",
        ],
        [
            "I believe my card ending in ",
            ("card_last4", "card_last4"),
            " has been skimmed or compromised",
        ],
        [
            "Anomalous activity: repeated requests for 2FA codes I did not trigger",
        ],
        [
            "online banking screen shows an unrecognized sign-in from unusual location",
        ],
        [
            "Multiple unauthorized passcode reset attempts reported for card ",
            ("card_last4", "card_last4"),
        ],
        [
            "Preventative alert regarding suspected phishing attack on credentials",
        ],
        [
            "I see strange access logs on my bank profile for ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "suspicion of atm card skimming on card ",
            ("card_last4", "card_last4"),
        ],
        [
            "Received fraudulent link via message asking for my account details",
        ],
        [
            "Security alert indicating consecutive failed biometric attempts",
        ],
        [
            "reporting abnormal behavior on bank profile with security warning flags",
        ],
        [
            "I suspect fraud after receiving multiple strange security texts today",
        ],
    ],
    "request_card_block": [
        [
            "Please freeze my card ending in ",
            ("card_last4", "card_last4"),
            " immediately",
        ],
        [
            "I want to temporarily lock my card ending in ",
            ("card_last4", "card_last4"),
            " for safety",
        ],
        ["pls block card ", ("card_last4", "card_last4"), " right now"],
        ["URGENT: block card number ", ("card_number", "card_number"), " immediately"],
        [
            "I want to suspend my card ending in ",
            ("card_last4", "card_last4"),
            " as a precaution",
        ],
        ["block my card ", ("card_last4", "card_last4"), " right away please"],
        [
            "Requesting an immediate block on my card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "Please put a security freeze on my card ending in ",
            ("card_last4", "card_last4"),
        ],
        ["pls block my card ", ("card_last4", "card_last4"), " so nobody can use it"],
        [
            "I need to deactivate my payment card ending in ",
            ("card_last4", "card_last4"),
        ],
        ["Block credit card ending in ", ("card_last4", "card_last4"), " immediately"],
        ["please freeze card ", ("card_last4", "card_last4"), " right now"],
        [
            "I want to turn off my card ending in ",
            ("card_last4", "card_last4"),
            " in your system",
        ],
        ["urgent card block requested for ", ("card_last4", "card_last4")],
        ["I request to cancel and block card ", ("card_number", "card_number")],
        [
            "For security reasons please block my debit card ending in ",
            ("card_last4", "card_last4"),
        ],
        ["deactivate my card ", ("card_last4", "card_last4"), " right this second"],
        [
            "I want to shut down and freeze my card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "can you block card ",
            ("card_last4", "card_last4"),
            " so no more payments go through",
        ],
        ["Immediate block for card ending in ", ("card_last4", "card_last4")],
    ],
    "request_dispute": [
        [
            "I need to file a formal dispute for the charge of ",
            ("currency", "currency"),
            ("amount", "amount"),
            " at ",
            ("merchant", "merchant"),
        ],
        [
            "I want to dispute the unauthorized transaction of ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " from ",
            ("merchant", "merchant"),
            " on ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "want to open a dispute for charge at ",
            ("merchant", "merchant"),
            " for ",
            ("currency", "currency"),
            ("amount", "amount"),
        ],
        [
            "I formally request a chargeback of ",
            ("currency", "currency"),
            ("amount", "amount"),
            " billed by ",
            ("merchant", "merchant"),
        ],
        [
            "I want to dispute a duplicate charge of ",
            ("currency", "currency"),
            ("amount", "amount"),
            " at ",
            ("merchant", "merchant"),
            " on card ",
            ("card_last4", "card_last4"),
        ],
        [
            "need refund of ",
            ("currency", "currency"),
            ("amount", "amount"),
            " charged by ",
            ("merchant", "merchant"),
            " please dispute it",
        ],
        [
            "Please initiate a chargeback claim for the transaction at ",
            ("merchant", "merchant"),
            " dated ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "Formal dispute for the erroneous debit of ",
            ("currency", "currency"),
            ("amount", "amount"),
            " from ",
            ("merchant", "merchant"),
        ],
        [
            "i want to appeal this transaction at ",
            ("merchant", "merchant"),
            " for ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
        ],
        [
            "I wish to open a dispute case regarding ",
            ("currency", "currency"),
            ("amount", "amount"),
            " charged by ",
            ("merchant", "merchant"),
        ],
        [
            "Initiate chargeback for purchase at ",
            ("merchant", "merchant"),
            " of ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
        ],
        [
            "requesting dispute for ",
            ("currency", "currency"),
            ("amount", "amount"),
            " at ",
            ("merchant", "merchant"),
            " posted on ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "I want to request a full refund dispute of ",
            ("currency", "currency"),
            ("amount", "amount"),
            " from ",
            ("merchant", "merchant"),
        ],
        [
            "Submitting claim for incorrect charge of ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " from ",
            ("merchant", "merchant"),
        ],
        [
            "dispute purchase at ",
            ("merchant", "merchant"),
            " on card ",
            ("card_last4", "card_last4"),
        ],
        [
            "I require a formal dispute opened for the ",
            ("currency", "currency"),
            ("amount", "amount"),
            " fee from ",
            ("merchant", "merchant"),
        ],
        [
            "I want to legally dispute and reverse the charge of ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " at ",
            ("merchant", "merchant"),
        ],
        [
            "opening dispute for chargeback with ",
            ("merchant", "merchant"),
            " of ",
            ("currency", "currency"),
            ("amount", "amount"),
        ],
        [
            "Requesting reimbursement dispute for ",
            ("merchant", "merchant"),
            " of ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
        ],
        [
            "Please process a chargeback dispute for ",
            ("currency", "currency"),
            ("amount", "amount"),
            " at ",
            ("merchant", "merchant"),
            " card ",
            ("card_last4", "card_last4"),
        ],
    ],
    "request_human_agent": [
        ["I want to speak with a human agent"],
        ["Transfer me to a real person please"],
        ["I need to talk to a human representative"],
        ["I do not want to talk to the automated bot"],
        ["Transfer me to a live specialist"],
        ["Human agent please"],
        ["I need to talk to a real person right now"],
        ["Can you connect me to an operator?"],
        ["Live representative please"],
        ["I need help from customer service personnel"],
        ["The bot does not understand me transfer me to human"],
        ["Please forward me to live agent support"],
        ["Could you connect me with a representative?"],
        ["I want to speak with support staff"],
        ["The robot is not helpful pass me to a human"],
        ["Live customer care agent urgent"],
        ["I would like to speak to an agent directly"],
        ["Connect to human support"],
        ["Get me a live agent as soon as possible"],
        ["Please route this conversation to a human advisor"],
        ["I need help from an actual human being"],
        ["Put me in touch with someone on the team"],
        ["Need professional assistance from a person"],
        ["Hand over to an operator"],
        ["No bots please I want a person"],
        ["Call up a human agent please"],
        ["Speak to live support agent"],
        ["Can I speak with a customer care supervisor?"],
        ["Direct me to human technical support"],
        ["Customer service operator please"],
        ["May I speak with a human specialist?"],
        ["I want a person made of flesh and blood"],
        ["Take me to your customer care team"],
        ["I need to chat with an actual person"],
        ["The bot is not solving my problem connect to agent"],
        ["Transfer this chat to an available representative"],
        ["I demand to speak to a human representative"],
        ["Connect me with customer support representative"],
        ["Personal service agent please"],
        ["I want to speak with a representative right away"],
    ],
    "provide_identity_data": [
        [
            "My name is ",
            ("full_name", "full_name"),
            ", document ",
            ("document_type", "document_type"),
            " number ",
            ("document_number", "document_number"),
        ],
        [
            "I am ",
            ("full_name", "full_name"),
            ", my document is ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            " and email ",
            ("email", "email"),
        ],
        [
            "my name is ",
            ("full_name", "full_name"),
            " birth date ",
            ("birth_date", "birth_date"),
            " phone ",
            ("phone", "phone"),
        ],
        [
            "Identity details: name ",
            ("full_name", "full_name"),
            ", ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", phone ",
            ("phone", "phone"),
        ],
        [
            "hi my name is ",
            ("full_name", "full_name"),
            " email is ",
            ("email", "email"),
            " and date of birth ",
            ("birth_date", "birth_date"),
        ],
        [
            "For verification: account holder ",
            ("full_name", "full_name"),
            ", ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", born on ",
            ("birth_date", "birth_date"),
        ],
        [
            "Confirming my identity: ",
            ("full_name", "full_name"),
            ", phone ",
            ("phone", "phone"),
            ", email ",
            ("email", "email"),
        ],
        [
            "my document is ",
            ("document_type", "document_type"),
            " number ",
            ("document_number", "document_number"),
            " under ",
            ("full_name", "full_name"),
        ],
        [
            "Customer verification: name ",
            ("full_name", "full_name"),
            ", card ",
            ("card_number", "card_number"),
            ", email ",
            ("email", "email"),
        ],
        [
            "Profile: ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", mobile ",
            ("phone", "phone"),
            ", DOB ",
            ("birth_date", "birth_date"),
        ],
        [
            "I identify as ",
            ("full_name", "full_name"),
            ", ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
        ],
        [
            "Here is my verification data: ",
            ("full_name", "full_name"),
            " and ID number ",
            ("document_number", "document_number"),
        ],
        [
            "full name ",
            ("full_name", "full_name"),
            ", type ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", email ",
            ("email", "email"),
        ],
        [
            "I am cardholder ",
            ("full_name", "full_name"),
            ", DOB ",
            ("birth_date", "birth_date"),
            ", phone ",
            ("phone", "phone"),
        ],
        [
            "document ",
            ("document_type", "document_type"),
            " with ID ",
            ("document_number", "document_number"),
            " belonging to ",
            ("full_name", "full_name"),
        ],
        [
            "info: ",
            ("full_name", "full_name"),
            ", ",
            ("email", "email"),
            ", ",
            ("phone", "phone"),
            ", ",
            ("document_number", "document_number"),
        ],
        [
            "Primary holder: ",
            ("full_name", "full_name"),
            ", doc type ",
            ("document_type", "document_type"),
            ", number ",
            ("document_number", "document_number"),
        ],
        [
            "hi i am ",
            ("full_name", "full_name"),
            ", card is ",
            ("card_number", "card_number"),
            " and email ",
            ("email", "email"),
        ],
        [
            "Identity info: ",
            ("full_name", "full_name"),
            ", date of birth ",
            ("birth_date", "birth_date"),
            ", document ",
            ("document_number", "document_number"),
        ],
        [
            "Providing my personal identity data: ",
            ("full_name", "full_name"),
            ", ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", phone ",
            ("phone", "phone"),
        ],
    ],
    "provide_otp_code": [
        ["The code I received via SMS is ", ("otp_code", "otp_code")],
        ["My one-time password is ", ("otp_code", "otp_code")],
        ["the otp code is ", ("otp_code", "otp_code")],
        ["I just received the verification code: ", ("otp_code", "otp_code")],
        ["Enter the code ", ("otp_code", "otp_code"), " that came to my phone"],
        ["verification code: ", ("otp_code", "otp_code")],
        ["The SMS token is ", ("otp_code", "otp_code")],
        ["Here is the code that arrived: ", ("otp_code", "otp_code")],
        ["Done, my security passcode is ", ("otp_code", "otp_code")],
        [
            "the code i got in the message is ",
            ("otp_code", "otp_code"),
            " please confirm",
        ],
        ["My received authorization code is ", ("otp_code", "otp_code")],
        ["Verification token: ", ("otp_code", "otp_code")],
        ["just received the dynamic code ", ("otp_code", "otp_code")],
        ["The OTP code sent to my mobile is ", ("otp_code", "otp_code")],
        ["I confirm using the passcode ", ("otp_code", "otp_code")],
        ["my otp is ", ("otp_code", "otp_code")],
        ["Temporary one-time code: ", ("otp_code", "otp_code")],
        ["The code sent to my phone is ", ("otp_code", "otp_code")],
        ["SMS passcode ", ("otp_code", "otp_code")],
        ["Providing the validation code received: ", ("otp_code", "otp_code")],
    ],
    "confirm": [
        ["Yes"],
        ["Yes I confirm"],
        ["Agreed"],
        ["Correct"],
        ["Yes please"],
        ["Yes proceed"],
        ["Confirmed"],
        ["I agree with this"],
        ["Go ahead"],
        ["Yes that is correct"],
        ["Sure I confirm"],
        ["Yes please proceed with that"],
        ["That is exactly my request"],
        ["Yes I authorize the operation"],
        ["Certainly I confirm"],
        ["Yes I want to continue"],
        ["That is right"],
        ["Yes please do it"],
        ["Completely agreed"],
        ["Affirmative"],
        ["Sure thing"],
        ["Yes I accept"],
        ["Correct do it now"],
        ["Yes proceed with the block"],
        ["Confirm action"],
        ["Yes go ahead with that"],
        ["Yes I confirm the indicated operation"],
        ["Please proceed"],
        ["Yes I am sure"],
        ["Let us do it"],
        ["Yes definitely"],
        ["Yes that is right go ahead"],
        ["Yes confirmed"],
        ["I confirm this request"],
        ["Yes I authorize"],
        ["Yes I wish to proceed"],
        ["Correct carry on"],
        ["Sounds good to me"],
        ["Yes confirm everything"],
        ["Agreed proceed"],
    ],
    "deny": [
        ["No never"],
        ["No I do not want to"],
        ["Cancel"],
        ["No cancel everything"],
        ["No I disagree"],
        ["Negative"],
        ["Not at all"],
        ["No do not proceed"],
        ["I do not authorize this"],
        ["Reject"],
        ["I do not want to continue"],
        ["Cancel that action"],
        ["No by no means"],
        ["That is not correct"],
        ["No please do not do that"],
        ["No cancel it"],
        ["Stop the process"],
        ["I am not sure better not"],
        ["No I do not wish to do that"],
        ["I reject the request"],
        ["Abort"],
        ["No thanks not at all"],
        ["No cancel my request"],
        ["No not that"],
        ["No that was not what happened"],
        ["Stop here"],
        ["No cancel operation"],
        ["I do not authorize this charge"],
        ["No I do not want to proceed"],
        ["No I do not agree"],
        ["No discard the request"],
        ["I prefer not to continue"],
        ["No reject that option"],
        ["Cancel order"],
        ["No I do not accept"],
        ["No that is wrong"],
        ["No please wait"],
        ["No leave it as is"],
        ["No stop everything"],
        ["No I changed my mind"],
    ],
    "check_balance": [
        [
            "What is the available balance on my card ending in ",
            ("card_last4", "card_last4"),
            "?",
        ],
        ["I would like to check the current balance of my account"],
        ["how much balance do i have on my card ", ("card_last4", "card_last4")],
        [
            "Good afternoon, can you tell me the available balance on card ending in ",
            ("card_last4", "card_last4"),
            "?",
        ],
        ["balance of card ", ("card_last4", "card_last4"), " please"],
        [
            "How much money do I have left on my card ending in ",
            ("card_last4", "card_last4"),
            "?",
        ],
        [
            "I want to know the available credit limit on card ",
            ("card_last4", "card_last4"),
        ],
        ["how much money is available on card ", ("card_last4", "card_last4")],
        [
            "Please provide the account balance for card ending in ",
            ("card_last4", "card_last4"),
        ],
        ["Balance inquiry for card ending in ", ("card_last4", "card_last4")],
        ["How much credit is available on card ", ("card_last4", "card_last4"), "?"],
        ["want to know my current balance for card ", ("card_last4", "card_last4")],
        ["Check balance for card ending in ", ("card_last4", "card_last4")],
        ["What is the current balance of my card ", ("card_last4", "card_last4"), "?"],
        ["available funds please on card ", ("card_last4", "card_last4")],
        ["I want to see how much money is in card ", ("card_last4", "card_last4")],
        ["Balance details for my card ", ("card_last4", "card_last4")],
        [
            "can you tell me the remaining balance on card ",
            ("card_last4", "card_last4"),
        ],
        ["How much can I spend on card ending in ", ("card_last4", "card_last4"), "?"],
        ["Check debit card balance ending in ", ("card_last4", "card_last4")],
    ],
    "check_recent_transactions": [
        [
            "I want to see the latest transactions on my card ending in ",
            ("card_last4", "card_last4"),
        ],
        ["Can you show me my recent account activity?"],
        ["want to see my latest purchases on card ", ("card_last4", "card_last4")],
        [
            "Good afternoon, I want to review purchase history for card ",
            ("card_last4", "card_last4"),
        ],
        ["latest transactions for card ", ("card_last4", "card_last4"), " please"],
        [
            "Please list the latest purchases made on my card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "What were the recent purchases made with card ",
            ("card_last4", "card_last4"),
            "?",
        ],
        ["show recent transactions for card ", ("card_last4", "card_last4")],
        [
            "I would like to check recent payments on card ending in ",
            ("card_last4", "card_last4"),
        ],
        ["Transaction statement for card ending in ", ("card_last4", "card_last4")],
        [
            "What are the recent charges posted to card ",
            ("card_last4", "card_last4"),
            "?",
        ],
        ["list recent transactions on card ", ("card_last4", "card_last4")],
        [
            "I want to review this week's activity on card ending in ",
            ("card_last4", "card_last4"),
        ],
        ["view recent statement for card ", ("card_last4", "card_last4")],
        [
            "Which charges have posted lately on my card ending in ",
            ("card_last4", "card_last4"),
            "?",
        ],
        [
            "Recent transaction history for debit card ending in ",
            ("card_last4", "card_last4"),
        ],
        ["show me recent purchases for card ", ("card_last4", "card_last4")],
        [
            "I want to see recent activity on card ending in ",
            ("card_last4", "card_last4"),
        ],
        ["Review recent transaction history on card ", ("card_last4", "card_last4")],
        [
            "Inquire about latest charges made on card ending in ",
            ("card_last4", "card_last4"),
        ],
    ],
    "greeting": [
        ["Hello"],
        ["Good morning"],
        ["Good afternoon"],
        ["Good evening"],
        ["Hi there how are you"],
        ["Hello good morning"],
        ["Hi I need some help"],
        ["Hello I have a quick question"],
        ["Hey there"],
        ["Hello hello"],
        ["Hello customer support team"],
        ["Good morning everyone"],
        ["Good afternoon team"],
        ["Hi folks"],
        ["Hello how is it going"],
        ["Hi I would like some information"],
        ["Good afternoon I need some assistance"],
        ["Hi good morning"],
        ["Hello hope you are doing well"],
        ["Hey how are things"],
        ["Warm greetings"],
        ["Hi is anyone available"],
        ["Good morning support"],
        ["Hello I would like to speak with someone"],
        ["Good afternoon how are you"],
        ["Hello starting chat session"],
        ["Hi I have an inquiry"],
        ["Hello good evening support"],
        ["Hi good morning please"],
        ["Hey good afternoon"],
        ["Hello team"],
        ["Hi everything good over there"],
        ["Good morning customer care"],
        ["Hello I need some guidance"],
        ["Good afternoon looking for assistance"],
        ["Hi wanting to ask a question"],
        ["Hello connecting with the bank"],
        ["Hey there good afternoon"],
        ["Good morning how are you guys today"],
        ["Hello customer service desk"],
    ],
    "out_of_scope": [
        ["What is the recipe for chocolate chip cookies?"],
        ["What is the weather like in New York today?"],
        ["Who won the 2002 World Cup?"],
        ["Tell me a funny joke"],
        ["What is the capital of Canada?"],
        ["Can you recommend a good action movie?"],
        ["How much does a flight to Paris cost?"],
        ["How do I fix a flat bicycle tire?"],
        ["Who painted the Mona Lisa?"],
        ["Write a short poem about the ocean"],
        ["What time is it in Tokyo right now?"],
        ["How do you make an espresso martini?"],
        ["How many planets are in our solar system?"],
        ["Help me with my high school math homework"],
        ["What is the best way to learn Python?"],
        ["Why is the sky blue during the day?"],
        ["Who walked on the moon first?"],
        ["What songs are trending right now?"],
        ["Translate this sentence to German"],
        ["What is the best Italian restaurant near here?"],
        ["How do I cure a common cold quickly?"],
        ["How fast does a cheetah run?"],
        ["How do I change the oil in my car?"],
        ["Who discovered penicillin?"],
        ["What is the highest mountain in North America?"],
        ["Tips for training for a marathon"],
        ["How to bake sourdough bread at home?"],
        ["How do solar panels generate electricity?"],
        ["What is the best-selling book of all time?"],
        ["What should I wear when it rains?"],
        ["How to grow fresh herbs in an apartment?"],
        ["Who invented the telephone?"],
        ["What is the deepest ocean trench on Earth?"],
        ["How do you tune an acoustic guitar?"],
        ["What movies are playing in theaters tonight?"],
        ["How far is the moon from the Earth?"],
        ["How to write a compelling resume?"],
        ["Why do leaves change color in autumn?"],
        ["What is the official currency of Switzerland?"],
        ["How do I make homemade pizza dough?"],
    ],
}

VAL_TEMPLATES: dict[str, list[Template]] = {
    "report_unrecognized_charge": [
        [
            "I completely dispute an unknown charge of ",
            ("currency", "currency"),
            ("amount", "amount"),
            " at ",
            ("merchant", "merchant"),
            " on card ",
            ("card_last4", "card_last4"),
        ],
        [
            "My card was charged ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " by ",
            ("merchant", "merchant"),
            " but I bought nothing",
        ],
        [
            "An unidentified debit of ",
            ("currency", "currency"),
            ("amount", "amount"),
            " from ",
            ("merchant", "merchant"),
            " appeared on ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "i see an unauthorized payment of ",
            ("currency", "currency"),
            ("amount", "amount"),
            " to ",
            ("merchant", "merchant"),
            " on card ",
            ("card_last4", "card_last4"),
        ],
        [
            "Dear support, I did not authorize the charge of ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " from ",
            ("merchant", "merchant"),
        ],
        [
            "I do not recognize the withdrawal of ",
            ("currency", "currency"),
            ("amount", "amount"),
            " by ",
            ("merchant", "merchant"),
            " on card ",
            ("card_last4", "card_last4"),
        ],
        [
            "Unknown purchase of ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " posted from ",
            ("merchant", "merchant"),
        ],
        [
            "Strange debit from ",
            ("merchant", "merchant"),
            " for ",
            ("currency", "currency"),
            ("amount", "amount"),
            " dated ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "i have no idea what this charge of ",
            ("currency", "currency"),
            ("amount", "amount"),
            " from ",
            ("merchant", "merchant"),
            " is",
        ],
        [
            "Fraudulent charge alert: ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " billed by ",
            ("merchant", "merchant"),
            " on card ",
            ("card_last4", "card_last4"),
        ],
    ],
    "report_lost_card": [
        [
            "I misplaced my debit card ending in ",
            ("card_last4", "card_last4"),
            " earlier this morning",
        ],
        [
            "I cannot find my card ending in ",
            ("card_last4", "card_last4"),
            ", I think it fell on the street",
        ],
        ["lost card ", ("card_last4", "card_last4"), " and need to report it lost"],
        [
            "I forgot where I left my card ending in ",
            ("card_last4", "card_last4"),
            " and it is missing",
        ],
        ["Notice of lost payment card with suffix ", ("card_last4", "card_last4")],
        [
            "I lost my card ending in ",
            ("card_last4", "card_last4"),
            " at the train station",
        ],
        ["Left my card ending in ", ("card_last4", "card_last4"), " at a retail store"],
        ["i lost my credit card ", ("card_number", "card_number"), " recently"],
        [
            "I have no idea where my card ending in ",
            ("card_last4", "card_last4"),
            " is located",
        ],
        [
            "Involuntary loss of payment card ending in ",
            ("card_last4", "card_last4"),
            " on the bus",
        ],
    ],
    "report_stolen_card": [
        [
            "I was robbed today and they took my debit card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "Someone snatched my card ending in ",
            ("card_last4", "card_last4"),
            " from my backpack",
        ],
        ["my card ", ("card_last4", "card_last4"), " was stolen please help me"],
        [
            "My card ending in ",
            ("card_last4", "card_last4"),
            " was stolen while on the train",
        ],
        [
            "Urgent alert: criminals took my card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "I was mugged on the street and lost possession of card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "Thieves stole my handbag with card ending in ",
            ("card_last4", "card_last4"),
            " inside",
        ],
        [
            "theft of card number ",
            ("card_number", "card_number"),
            " during the evening",
        ],
        [
            "Someone just robbed me and took my card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "Formal notification of violent robbery of card ending in ",
            ("card_last4", "card_last4"),
        ],
    ],
    "report_suspicious_activity": [
        [
            "I noticed suspicious activity on card ",
            ("card_last4", "card_last4"),
            " with system security warnings",
        ],
        [
            "Alert regarding unauthorized sign-in attempt on my online account",
        ],
        [
            "warning about unrecognized login and access on ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "I strongly suspect someone is trying to clone my card ",
            ("card_last4", "card_last4"),
        ],
        [
            "Security alert regarding phishing SMS attempting to steal credentials",
        ],
        [
            "Suspicious activity: received one-time passcode without asking for one",
        ],
        [
            "think my card ",
            ("card_last4", "card_last4"),
            " was skimmed at a suspicious atm",
        ],
        [
            "Strange attempt to change account contact details that I did not start",
        ],
        [
            "Preventative report of possible tampering or fraud on card ",
            ("card_last4", "card_last4"),
        ],
        [
            "Bank alert about multiple failed login attempts from unknown location",
        ],
    ],
    "request_card_block": [
        [
            "Please immediately deactivate my card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "I urgently need to lock my debit card ending in ",
            ("card_last4", "card_last4"),
        ],
        ["block card ", ("card_last4", "card_last4"), " as soon as possible"],
        [
            "I request an immediate freeze on my card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "Go ahead and block my payment card with last digits ",
            ("card_last4", "card_last4"),
        ],
        [
            "I want to deactivate my card number ",
            ("card_number", "card_number"),
            " without delay",
        ],
        ["please freeze it now, card ending in ", ("card_last4", "card_last4")],
        [
            "Place a total security block on card ending in ",
            ("card_last4", "card_last4"),
        ],
        ["I want to suspend all transactions on card ", ("card_last4", "card_last4")],
        ["Emergency block request for card ending in ", ("card_last4", "card_last4")],
    ],
    "request_dispute": [
        [
            "I am requesting a formal chargeback for ",
            ("currency", "currency"),
            ("amount", "amount"),
            " charged by ",
            ("merchant", "merchant"),
        ],
        [
            "I wish to dispute the transaction of ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " at ",
            ("merchant", "merchant"),
            " on ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "open dispute for purchase at ",
            ("merchant", "merchant"),
            " for ",
            ("currency", "currency"),
            ("amount", "amount"),
        ],
        [
            "I demand a refund and dispute investigation for ",
            ("currency", "currency"),
            ("amount", "amount"),
            " from ",
            ("merchant", "merchant"),
        ],
        [
            "Please initiate a dispute for the charge from ",
            ("merchant", "merchant"),
            " on card ",
            ("card_last4", "card_last4"),
        ],
        [
            "I want to open a formal dispute process against ",
            ("merchant", "merchant"),
            " for ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
        ],
        [
            "Chargeback claim for the debit of ",
            ("currency", "currency"),
            ("amount", "amount"),
            " at ",
            ("merchant", "merchant"),
        ],
        [
            "I contest the payment to ",
            ("merchant", "merchant"),
            " totaling ",
            ("amount", "amount"),
            " ",
            ("currency", "currency"),
            " from ",
            ("transaction_date", "transaction_date"),
        ],
        [
            "request for chargeback on transaction from ",
            ("merchant", "merchant"),
            " of ",
            ("currency", "currency"),
            ("amount", "amount"),
        ],
        [
            "Claim to reverse charge billed by ",
            ("merchant", "merchant"),
            " on card ending in ",
            ("card_last4", "card_last4"),
        ],
    ],
    "request_human_agent": [
        ["Please transfer me to a live customer service representative"],
        ["I want to speak directly with an actual human"],
        ["Connect me with a live support agent immediately"],
        ["Route this conversation to an agent please"],
        ["I need assistance from a human support specialist"],
        ["The chatbot cannot resolve my issue transfer me"],
        ["I want to be assisted by an actual person on the team"],
        ["Please connect me to an available advisor"],
        ["Pass this chat to customer service staff"],
        ["I need to talk to a human operator right now"],
    ],
    "provide_identity_data": [
        [
            "Identity verification: my name is ",
            ("full_name", "full_name"),
            ", ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", email ",
            ("email", "email"),
        ],
        [
            "My details are ",
            ("full_name", "full_name"),
            ", born on ",
            ("birth_date", "birth_date"),
            " and phone ",
            ("phone", "phone"),
        ],
        [
            "here are my details ",
            ("full_name", "full_name"),
            " ID ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
        ],
        [
            "Account holder name ",
            ("full_name", "full_name"),
            ", phone ",
            ("phone", "phone"),
            ", ID ",
            ("document_number", "document_number"),
        ],
        [
            "Submitting my ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", email ",
            ("email", "email"),
            " and DOB ",
            ("birth_date", "birth_date"),
        ],
        [
            "Primary holder ",
            ("full_name", "full_name"),
            ", card ",
            ("card_number", "card_number"),
            ", phone ",
            ("phone", "phone"),
        ],
        [
            "identification ",
            ("full_name", "full_name"),
            " with doc ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            " and email ",
            ("email", "email"),
        ],
        [
            "Holder records: ",
            ("full_name", "full_name"),
            ", born ",
            ("birth_date", "birth_date"),
            ", ID ",
            ("document_number", "document_number"),
        ],
        [
            "Registration info: ",
            ("full_name", "full_name"),
            ", ",
            ("document_type", "document_type"),
            " ",
            ("document_number", "document_number"),
            ", mobile ",
            ("phone", "phone"),
        ],
        [
            "Identification for authentication: ",
            ("full_name", "full_name"),
            ", date of birth ",
            ("birth_date", "birth_date"),
            ", email ",
            ("email", "email"),
        ],
    ],
    "provide_otp_code": [
        ["The confirmation number received via text is ", ("otp_code", "otp_code")],
        ["My one-time passcode to authorize this action is ", ("otp_code", "otp_code")],
        ["got the otp code it is ", ("otp_code", "otp_code")],
        ["Providing temporary verification code: ", ("otp_code", "otp_code")],
        ["Security passcode received on my mobile device: ", ("otp_code", "otp_code")],
        ["The code sent via SMS to my phone is ", ("otp_code", "otp_code")],
        ["Dynamic security token received: ", ("otp_code", "otp_code")],
        ["here is the otp code ", ("otp_code", "otp_code")],
        ["Entering temporary authorization code ", ("otp_code", "otp_code")],
        ["SMS authorization token: ", ("otp_code", "otp_code")],
    ],
    "confirm": [
        ["Definitely I confirm this"],
        ["Yes I am in complete agreement"],
        ["Go ahead and proceed with the operation"],
        ["Yes that is exactly right"],
        ["I confirm all of this information"],
        ["Yes please keep going"],
        ["I confirm this request completely"],
        ["Correct proceed immediately"],
        ["I accept and authorize this"],
        ["Yes 100 percent confirmed"],
    ],
    "deny": [
        ["No I decline this procedure"],
        ["No cancel that right now"],
        ["Cancel I do not want to proceed"],
        ["No I totally disagree with that"],
        ["No void this request"],
        ["Do not do that please cancel"],
        ["No absolutely not"],
        ["I reject that suggestion"],
        ["No do not authorize"],
        ["No I do not want that to happen"],
    ],
    "check_balance": [
        [
            "Could you tell me the remaining balance on card ending in ",
            ("card_last4", "card_last4"),
            "?",
        ],
        ["I would like to verify the funds in my card ", ("card_last4", "card_last4")],
        ["check balance for card ", ("card_last4", "card_last4"), " now"],
        [
            "What is the total remaining balance on card ending in ",
            ("card_last4", "card_last4"),
            "?",
        ],
        [
            "I want to check how much spending limit is left on card ",
            ("card_last4", "card_last4"),
        ],
        [
            "Kindly inform me about the current balance of card ",
            ("card_last4", "card_last4"),
        ],
        [
            "how much money is currently on card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "Account balance verification request for card ",
            ("card_last4", "card_last4"),
        ],
        [
            "What is the available sum on card ending in ",
            ("card_last4", "card_last4"),
            "?",
        ],
        ["Inquire about funds available on debit card ", ("card_last4", "card_last4")],
    ],
    "check_recent_transactions": [
        [
            "Could you detail the latest transactions on card ending in ",
            ("card_last4", "card_last4"),
            "?",
        ],
        [
            "I would like to check this week's charges on card ",
            ("card_last4", "card_last4"),
        ],
        ["view recent purchases on card ", ("card_last4", "card_last4")],
        [
            "Please display the recent debits posted to card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "I want to view the transaction summary for card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "Which transactions were processed recently on card ",
            ("card_last4", "card_last4"),
            "?",
        ],
        [
            "Reviewing transactions from the past few days for card ",
            ("card_last4", "card_last4"),
        ],
        [
            "display recent charges on card ",
            ("card_last4", "card_last4"),
            " this month",
        ],
        [
            "Debit and purchase transaction log for card ending in ",
            ("card_last4", "card_last4"),
        ],
        [
            "List of approved transactions on card ending in ",
            ("card_last4", "card_last4"),
        ],
    ],
    "greeting": [
        ["Hello good morning to everybody"],
        ["Very pleasant afternoon"],
        ["Hello best wishes to the support team"],
        ["Good afternoon bank support"],
        ["Hi I have a couple of questions about my account"],
        ["Good morning I wish to make an inquiry"],
        ["Hello good afternoon looking for some assistance"],
        ["Good evening to the support staff"],
        ["Hello hope your day is going well"],
        ["Warm greetings to the customer service team"],
    ],
    "out_of_scope": [
        ["What is the longest river in the world?"],
        ["How do you prepare authentic sushi at home?"],
        ["Who wrote To Kill a Mockingbird?"],
        ["What is the distance between Mars and Earth?"],
        ["How to take care of succulent plants indoors?"],
        ["What is the capital of Australia?"],
        ["How can I learn to play keyboard by myself?"],
        ["Who invented the television?"],
        ["Why do solar eclipses occur?"],
        ["Best yoga stretches for total beginners"],
    ],
}
