"""Generator for contracts/labels.py from data/eval/synthetic/schema.yaml."""

import re
import sys
from pathlib import Path


def parse_schema_yaml(schema_path: Path | str) -> tuple[list[str], list[str]]:
    """Parse intent and slot names from schema.yaml without external dependencies."""
    path = Path(schema_path)
    if not path.is_file():
        raise FileNotFoundError(f"schema.yaml not found at {path}")

    content = path.read_text(encoding="utf-8")
    intents: list[str] = []
    slots: list[str] = []

    current_section: str | None = None
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue

        if line == "intents:":
            current_section = "intents"
            continue
        elif line == "slots:":
            current_section = "slots"
            continue
        elif (
            not line.startswith("-")
            and line.endswith(":")
            and not any(
                line.startswith(prefix)
                for prefix in (
                    "name:",
                    "pii:",
                    "pattern:",
                    "description:",
                    "notes:",
                    "normalized:",
                    "languages:",
                )
            )
        ):
            current_section = None

        match = re.match(r"^-\s+name:\s*([A-Za-z0-9_]+)", line)
        if match:
            item_name = match.group(1)
            if current_section == "intents":
                intents.append(item_name)
            elif current_section == "slots":
                slots.append(item_name)

    if not intents:
        raise ValueError("No intents found in schema.yaml")
    if not slots:
        raise ValueError("No slots found in schema.yaml")

    return intents, slots


def generate_labels_code(schema_path: Path | str) -> str:
    """Generate typed labels Python module content from schema.yaml."""
    intents, slots = parse_schema_yaml(schema_path)

    lines: list[str] = [
        '"""Typed label definitions generated from data/eval/synthetic/schema.yaml.',
        "",
        "DO NOT EDIT MANUALLY. Generated by contracts.generate_labels.",
        '"""',
        "",
        "from enum import StrEnum",
        "from typing import Any",
        "",
        "",
        "class Intent(StrEnum):",
        '    """Customer intent labels matching schema.yaml."""',
        "",
    ]

    for intent in intents:
        member_name = intent.upper()
        lines.append(f'    {member_name} = "{intent}"')

    lines.extend(
        [
            "",
            "",
            "class SlotType(StrEnum):",
            '    """Slot entity types matching schema.yaml."""',
            "",
        ]
    )

    for slot in slots:
        member_name = slot.upper()
        lines.append(f'    {member_name} = "{slot}"')

    lines.extend(
        [
            "",
            "    @classmethod",
            "    def _missing_(cls, value: object) -> Any:",
            "        if isinstance(value, str):",
            "            val_lower = value.lower()",
            "            for member in cls:",
            "                if member.value == val_lower or member.name.lower() == val_lower:",
            "                    return member",
            "        return super()._missing_(value)",
        ]
    )

    lines.extend(
        [
            "",
            "",
            "class PiiType(StrEnum):",
            '    """PII category types matching orchestrator masking placeholders."""',
            "",
            '    DOC = "DOC"',
            '    NAME = "NAME"',
            '    PHONE = "PHONE"',
            '    EMAIL = "EMAIL"',
            '    CARD = "CARD"',
            '    DATE = "DATE"',
            '    OTP = "OTP"',
            "",
            "    @classmethod",
            "    def _missing_(cls, value: object) -> Any:",
            "        if isinstance(value, str):",
            "            val_upper = value.upper()",
            "            for member in cls:",
            "                if member.value == val_upper or member.name == val_upper:",
            "                    return member",
            "        return super()._missing_(value)",
            "",
        ]
    )

    return "\n".join(lines)


def main() -> None:
    """Generate contracts/labels.py from schema.yaml."""
    current = Path(__file__).resolve().parent
    repo_root = current
    for parent in [current, *current.parents]:
        if (parent / "pyproject.toml").is_file() and (parent / "data").is_dir():
            repo_root = parent
            break

    schema_path = repo_root / "data" / "eval" / "synthetic" / "schema.yaml"
    target_path = Path(__file__).resolve().parent / "labels.py"

    if not schema_path.is_file():
        print(f"Error: schema.yaml not found at {schema_path}", file=sys.stderr)
        sys.exit(1)

    code = generate_labels_code(schema_path)
    target_path.write_text(code, encoding="utf-8")
    print(f"Generated {target_path} successfully from {schema_path}.")


if __name__ == "__main__":
    main()
