"""Typed label definitions generated from data/eval/synthetic/schema.yaml.

DO NOT EDIT MANUALLY. Generated by contracts.generate_labels.
"""

from enum import StrEnum
from typing import Any


class Intent(StrEnum):
    """Customer intent labels matching schema.yaml."""

    REPORT_UNRECOGNIZED_CHARGE = "report_unrecognized_charge"
    REPORT_LOST_CARD = "report_lost_card"
    REPORT_STOLEN_CARD = "report_stolen_card"
    REPORT_SUSPICIOUS_ACTIVITY = "report_suspicious_activity"
    REQUEST_CARD_BLOCK = "request_card_block"
    REQUEST_DISPUTE = "request_dispute"
    REQUEST_HUMAN_AGENT = "request_human_agent"
    PROVIDE_IDENTITY_DATA = "provide_identity_data"
    PROVIDE_OTP_CODE = "provide_otp_code"
    CONFIRM = "confirm"
    DENY = "deny"
    CHECK_BALANCE = "check_balance"
    CHECK_RECENT_TRANSACTIONS = "check_recent_transactions"
    GREETING = "greeting"
    OUT_OF_SCOPE = "out_of_scope"


class SlotType(StrEnum):
    """Slot entity types matching schema.yaml."""

    DOCUMENT_TYPE = "document_type"
    DOCUMENT_NUMBER = "document_number"
    FULL_NAME = "full_name"
    BIRTH_DATE = "birth_date"
    EMAIL = "email"
    PHONE = "phone"
    CARD_LAST4 = "card_last4"
    CARD_NUMBER = "card_number"
    AMOUNT = "amount"
    CURRENCY = "currency"
    MERCHANT = "merchant"
    TRANSACTION_DATE = "transaction_date"
    OTP_CODE = "otp_code"

    @classmethod
    def _missing_(cls, value: object) -> Any:
        if isinstance(value, str):
            val_lower = value.lower()
            for member in cls:
                if member.value == val_lower or member.name.lower() == val_lower:
                    return member
        return super()._missing_(value)


class PiiType(StrEnum):
    """PII category types matching orchestrator masking placeholders."""

    DOC = "DOC"
    NAME = "NAME"
    PHONE = "PHONE"
    EMAIL = "EMAIL"
    CARD = "CARD"
    DATE = "DATE"
    OTP = "OTP"
    SECRET = "SECRET"

    @classmethod
    def _missing_(cls, value: object) -> Any:
        if isinstance(value, str):
            val_upper = value.upper()
            for member in cls:
                if member.value == val_upper or member.name == val_upper:
                    return member
        return super()._missing_(value)
